[SAGE-1069] Statbox add optional icon
Kajabi/sage-lib pull request #1070
Opened 2021-12-03 16:28 UTC by QuintonJason

## Description

[SAGE-1069](https://github.com/Kajabi/sage-lib/issues/1069)

## Screenshots

|  Before  |  After  |
|--------|--------|
|did not exist|![Screen Shot 2021-12-03 at 8 51 06 AM](https://user-images.githubusercontent.com/1241836/144637333-09c3c7eb-ec54-4ff4-b733-86b24102efbf.png)|

## Testing in `sage-lib`

Go to the Rails Statbox page and scroll down to the `Simple with Icon` example and verify 
Go to the Storybook `Statbox -> Simple with Icon` example and verify

## Testing in `kajabi-products`

1. (**LOW**) New property. Has no affect in the app

## Related

Closes [SAGE-1069](https://github.com/Kajabi/sage-lib/issues/1069)

2021-12-05 20:54 UTC, monicawheeler commented on packages/sage-assets/lib/stylesheets/components/_stat_box.scss
>    // Styles here
It appears that there are some spacing differences in Sage 3.0 Stat Box and what is currently in the system. Could we adjust those differences in this PR? Specifically:
* the padding on the `sage-stat-box` shows to be top/bottom as 18px and left/right as 16px
* the right margin on the `icon` and the `img`

2021-12-05 20:54 UTC, monicawheeler commented on packages/sage-assets/lib/stylesheets/components/_stat_box.scss
> +  margin-right: sage-spacing(xs);
It appears that there are some spacing differences in Sage 3.0 Stat Box and what is currently in the system. Could we adjust those differences in this PR? Specifically:
* the right margin on the `icon` and the `img`

2021-12-06 17:54 UTC, monicawheeler commented on packages/sage-assets/lib/stylesheets/components/_stat_box.scss
> +  padding: rem(18px) sage-spacing(sm);
🙌 The spacing looks great, but now the `.sage-stat-box__img img` appears too small. Perhaps we should investigate why it's necessary to use `position: aboslute` for this selector when the `stat-box` is in a grid.

<img width="698" alt="Screen Shot 2021-12-06 at 11 52 04 AM" src="https://user-images.githubusercontent.com/24237393/144896956-d5083060-eeb5-4c3f-aec5-72ceab1eac55.png">

2021-12-08 15:56 UTC, philschanely approved these changes

2021-12-08 17:49 UTC, monicawheeler requested changes
Added a comment in the `_stat_box.scss` file.

2021-12-13 16:36 UTC, merged