[Modal] - add position relative to fullscreen modal
Kajabi/sage-lib pull request #1186
Opened 2022-01-31 15:29 UTC by QuintonJason

## Description

- [x] add `position: relative` to be sure `z-index` is always behaving properly 

## Screenshots

|  Before  |  After  |
|--------|--------|
|||

## Testing in `sage-lib`

## Testing in `kajabi-products`

1. (**LOW/MEDIUM/HIGH/BREAKING**) Description of the change and its impact with QA as the audience.
   - [ ] One more examples of the component in use to either test the change or verify the change has not had adverse effects.

## Related

2022-02-01 20:40 UTC, pixelflips approved these changes
LGTM!

2022-02-02 01:55 UTC, monkeypox8 requested changes
Small typo in the token use, should be good to go once that's cleared up though!

Something that we might want to look into later is applying `overscroll-behavior` on modals as default behavior. No Safari support yet, but it could be useful to lock the background page from scrolling.

2022-02-02 01:55 UTC, monkeypox8 commented on packages/sage-assets/lib/stylesheets/components/_modal.scss
> +    z-index: sage-z-indexes(default, 1);
Should this be `sage-z-index`?

2022-02-02 15:59 UTC, QuintonJason commented on packages/sage-assets/lib/stylesheets/components/_modal.scss
> +    z-index: sage-z-indexes(default, 1);
@monkeypox8 nice catch. Pushed a fix

2022-02-02 17:11 UTC, monkeypox8 approved these changes
👍🏼 LGTM!

2022-02-04 02:26 UTC, merged