[Sage-171] Stat Box - Slots Update
Kajabi/sage-lib pull request #1188
Opened 2022-01-31 18:43 UTC by anechol

## Description

Updates Stat Box component with new props and slots for aded flexibility.

## Screenshots

|  Before  |  After  |
|--------|--------|
WIP|WIP

## Testing in `sage-lib`

WIP

## Testing in `kajabi-products`

WIP

## Related

[Sage-171](https://kajabi.atlassian.net/browse/SAGE-171)

2022-02-07 14:31 UTC, philschanely commented
@monkeypox8 regarding implementation implications of this breaking change, there appear to be only two places this component is currently instantiated (plus at least one more in the works for the Payments Index page). These would need to be patched since they rely on current props:

- `app/javascript/apps/manage/insights/Insights.jsx` ~line 41 and in related files 
  - `app/javascript/apps/manage/insights/contacts/dataHelper.jsx`
  - `app/javascript/apps/manage/insights/dataHelper.jsx`
- `app/views/admin/shared/_email_stat_box.html.erb` ~line 77

I will approve the PR as I don't have any concerns about the work itself but @anechol I assume you will not merge until we have an implementation plan in place.

2022-02-07 14:42 UTC, philschanely requested changes
Really nice work on this @anechol especially in the description laying out the breaking changes! 🙇‍♂️  I have a request regarding the grid area usage noted below for review before 👍  but loving this direction, use of slots, and simplification over all.

2022-02-07 14:42 UTC, philschanely commented on packages/sage-assets/lib/stylesheets/components/_stat_box.scss
> +  grid-template-areas:
Love this idea; very powerful tool for microlayouts.

One downside in a flexible component like this is that it tends to force all the slots to appear even if we don't provided content for them. This can lead to extra spacing that is undesired. Consider using some `--modifiers` that you toggle on in the view to govern a few different layouts (presence or absence of footer for example).

Honestly its a situation in general with this component that makes me wonder about creating some form of a css grid area utility so as to provide custom grid layouts in some fashion.

2022-02-07 14:42 UTC, philschanely commented on packages/sage-assets/lib/stylesheets/components/_stat_box.scss
> +.sage-stat-box__button,
Is this still in use?

2022-02-07 15:29 UTC, anechol commented on packages/sage-assets/lib/stylesheets/components/_stat_box.scss
> +.sage-stat-box__button,
Ahhh, thanks! I've updated this

2022-02-07 20:00 UTC, philschanely approved these changes
Looking great!

2022-02-07 20:17 UTC, QuintonJason commented
Looking good. I have a question related to the title text. Does it stretch to the end of the line of is it confined to a certain portion of the top row. Looking at the sage 3 design files, I'm not able to tell as nothing wraps so I may need input from design. There's so much white space around the label that I'm not sure if there will be the intention of adding additional things. This may be more for design, but I'd hate to hold up your PR while finding these answers

2022-02-07 20:39 UTC, anechol commented
> Looking good. I have a question related to the title text. Does it stretch to the end of the line of is it confined to a certain portion of the top row. Looking at the sage 3 design files, I'm not able to tell as nothing wraps so I may need input from design. There's so much white space around the label that I'm not sure if there will be the intention of adding additional things. This may be more for design, but I'd hate to hold up your PR while finding these answers

Thanks for bringing this up @QuintonJason. This PR won't be merged until there's a patch to address breaking changes in `kp` so if there needs to be any updates, I can still address those as necessary.

2022-02-09 01:23 UTC, monkeypox8 approved these changes
👍🏼 LGTM, great work! Just a heads-up that this branch will need to be rebased for the breaking change in `develop` or storybook will freeze/loop.

Corresponding PR for `kajabi-products` to be addressed in SAGE-234.

2022-02-10 15:14 UTC, monicawheeler approved these changes
Great work here!

2022-03-28 21:40 UTC, anechol commented
Closed as Jira ticket has been archived.

2022-03-28 21:40 UTC, closed without merging