[Sage-208] Link - Foundations Update
Kajabi/sage-lib pull request #1202
Opened 2022-02-08 22:28 UTC by anechol

## Description

Updates Link component with the following:
- Adds `text-decoration: underline`

## Screenshots

|  Before  |  After  |
|--------|--------|
WIP|WIP

## Testing in `sage-lib`

WIP

## Testing in `kajabi-products`

(LOW) Visual updates for Link component

## Related

[Sage-208](https://kajabi.atlassian.net/browse/SAGE-208)

2022-02-22 20:37 UTC, monicawheeler commented on packages/sage-assets/lib/stylesheets/components/_link.scss
> +  text-decoration: none;
This selector is losing on specificity and not getting applied.
![Screen Shot 2022-02-22 at 2 35 38 PM](https://user-images.githubusercontent.com/24237393/155215100-c537fe27-09f9-45ce-8611-97a80bb98341.png)

2022-02-22 20:38 UTC, monicawheeler requested changes
Help icon is still receiving underline, added a note in the CSS.

2022-02-22 22:59 UTC, anechol commented
> Help icon is still receiving underline, added a note in the CSS.

@monicawheeler I'm making a minor update to prevent the specificity issue, but it looks like removing the underline from the icon only will require some interesting updates to the `display` property, namely changing both the link and the `::before` to `inline-block`. We have a ticket open to either deprecate or repurpose the help and launch variants. Given that, would it be worth making this potentially temporary change now and changing it back after a decision has been made on whether to deprecate the variant? I can definitely do this and don't see any adverse effects save for having to manually adjust icon alignment with margins. Let me know your thoughts.

2022-02-23 15:38 UTC, monicawheeler commented
@anechol - given that we have a ticket open to deal with the help and launch variants, this request can be ignored. In addition, what do you think about removing the help/info link examples in the documentation site?

2022-02-23 15:39 UTC, monicawheeler approved these changes
Updated to Approved. Non-blocking note in the comments. Thanks for your consideration and great work!

2022-02-23 15:39 UTC, anechol commented
> Updated to Approved. Non-blocking note in the comments. Thanks for your consideration and great work!

@monicawheeler Yep, I can definitely remove the examples for now.

2022-02-23 21:21 UTC, pixelflips approved these changes
LGTM! :shipit:

2022-02-23 22:49 UTC, merged