[SAGE-203] Button update
Kajabi/sage-lib pull request #1204
Opened 2022-02-09 01:58 UTC by QuintonJason

## Description

- [x] remove `raised` prop

## Screenshots

|  Before  |  After  |
|--------|--------|
|||

## Testing in `sage-lib`

## Testing in `kajabi-products`

1. (**LOW/MEDIUM/HIGH/BREAKING**) Description of the change and its impact with QA as the audience.
   - [ ] One more examples of the component in use to either test the change or verify the change has not had adverse effects.

## Related

Closes [SAGE-203](https://kajabi.atlassian.net/browse/SAGE-203)

2022-02-22 20:45 UTC, monicawheeler commented on packages/sage-assets/lib/stylesheets/components/_button.scss
> +  // padding: 0;
Is this a line that can be removed? Or should we have a comment there to indicate why it's commented out?

2022-02-22 20:45 UTC, monicawheeler commented on packages/sage-assets/lib/stylesheets/components/_button.scss
>        // TODO: refactor the subtle button hover state, after Sage 3.0 conversion
For this TODO text, is this something that can be removed now?

2022-02-22 20:49 UTC, monicawheeler commented on packages/sage-assets/lib/stylesheets/core/mixins/_sage.scss
> +  $focus-shadow: #8ECAFB,
Are we able to convert this hex value to `sage-color(primary, 400)`?

2022-02-22 20:51 UTC, monicawheeler requested changes
Great work here! I've added a couple small items

2022-02-22 20:57 UTC, monicawheeler approved these changes
💯 great work!

2022-02-22 21:39 UTC, philschanely approved these changes
Solid work here! 🙌

2022-02-22 22:09 UTC, pixelflips approved these changes
LGTM! 👍🏼  Great work.

Not a showstopper at all, but I notice the not-allowed cursor is not being applied to the disabled buttons anymore. This also happens on the prod version. Just adding a note here as a reminder to create a follow-up.

2022-02-22 23:08 UTC, anechol requested changes
Looking very good Quinton! One minor thing. The font weights for this font are a bit weird. They're listed as `medium` in Figma when `medium` should be `semibold`. If you see anything labeled as Book, that would be the correct `medium` weight.

2022-02-23 00:44 UTC, QuintonJason commented
> Looking very good Quinton! One minor thing. The font weights for this font are a bit weird. They're listed as `medium` in Figma when `medium` should be `semibold`. If you see anything labeled as Book, that would be the correct `medium` weight.

🔬 💯

2022-02-23 15:26 UTC, merged