[SAGE-235] Dropdown width
Kajabi/sage-lib pull request #1205
Opened 2022-02-09 18:24 UTC by joedakroub

## Description
This PR replaces the `panelMaxWidth` prop with `panelWidth` in the React DropdownPanel to better match how the Rails version works.

This enables one to use `panelWidth: "500px"` to be able to set a custom width. The custom width does not override the `min-width` setting however.

## Testing in `sage-lib`
1. Visit http://0.0.0.0:4100/?path=/story/sage-dropdown--default
2. Ensure that the `panelSize` and `panelWidth` settings work as expected

## Testing in `kajabi-products`
Please test any area in KP that uses React dropdowns:

1. (**MED**) Contacts
   - [ ] http://www.kajabi.test:3000/admin/sites/1/contacts
  
## Related
https://kajabi.atlassian.net/browse/SAGE-235

2022-02-09 18:24 UTC, joedakroub commented on packages/sage-react/lib/Dropdown/DropdownPanel.jsx
> +      [`sage-dropdown__panel--custom-width`]: width,
This matches the Rails implementation.

2022-02-09 18:24 UTC, joedakroub commented on packages/sage-react/lib/Dropdown/DropdownPanel.jsx
> +        "--custom-panel-width": width,
This matches the Rails implementation.

2022-02-09 22:10 UTC, monicawheeler approved these changes
🙌🏻

2022-02-10 00:42 UTC, philschanely requested changes
@joedakroub while these changes make sense I'm hesitant to remove the changed props altogether without an audit of uses to first ensure we're not creating a regression. Also, the ticket perhaps was not clear enough that the hope was to add ability to control the dropdown trigger size, not adjust how the panel size is controlled. I'll update the ticket wording for clarity. Sorry about that!

2022-02-28 22:30 UTC, closed without merging