[Sage-210] Form Textarea - Foundations Update
Kajabi/sage-lib pull request #1206
Opened 2022-02-09 23:05 UTC by anechol

## Description

Updates the Form Textarea component:
- Adjusts padding inside input
- Adjusts margin for labels
- Removes icon from help messages

## Screenshots

|  Before  |  After  |
|--------|--------|
WIP|WIP

## Testing in `sage-lib`

WIP

## Testing in `kajabi-products`

WIP

## Related

[Sage-210](https://kajabi.atlassian.net/browse/SAGE-210)

2022-02-22 21:48 UTC, philschanely approved these changes
Looks really great. Ticket is fulfilled from my angle. 🙌

2022-02-23 21:12 UTC, monicawheeler commented on packages/sage-assets/lib/stylesheets/core/mixins/_sage.scss
> +  border-radius: rem(10px);
It looks like inputs use `10px` as a `border-radius` as well. It would be worth adding within the `_border.scss` file as a variable. @QuintonJason may have done this in his input work.

2022-02-23 21:14 UTC, monicawheeler requested changes
Great work! One minor consideration prior to merging noted inline.

2022-02-23 21:18 UTC, QuintonJason commented on packages/sage-assets/lib/stylesheets/core/mixins/_sage.scss
> +  border-radius: rem(10px);
> It looks like inputs use `10px` as a `border-radius` as well. It would be worth adding within the `_border.scss` file as a variable. @QuintonJason may have done this in his input work.

@monicawheeler @anechol since your PR is close and mine is still in draft, merge yours and I'll rebase accordingly.

2022-02-23 21:34 UTC, pixelflips approved these changes
LGTM! 👍🏼 

Not a showstopper here but one thing we may need to note as a follow-up somewhere is that the markup restructure here will need to be applied in `kp` as well in relation to simpleform. Seems there are around 10 or so instances that use the previous structure (label after textarea).

2022-02-23 21:40 UTC, anechol commented
> LGTM! 👍🏼
> 
> Not a showstopper here but one thing we may need to note as a follow-up somewhere is that the markup restructure here will need to be applied in `kp` as well in relation to simpleform. Seems there are around 10 or so instances that use the previous structure (label after textarea).

Oh, thank you for that callout! I'll add that in the description and look into making a follow-up ticket.

2022-02-23 22:15 UTC, monicawheeler approved these changes
👍🏻  Thanks Ashley! :shipit:

2022-02-23 22:21 UTC, merged