[Sage-212] Form Select - Foundations Update
Kajabi/sage-lib pull request #1207
Opened 2022-02-11 19:50 UTC by anechol

## Description

Updates Form Select component:
- Adjusts margin for labels to `margin-bottom: 6px`
- Moves label markup above select input in both React and Rails
- Removes floating label
- Removes icon from help messages

## Screenshots

|  Before  |  After  |
|--------|--------|
WIP|WIP

## Testing in `sage-lib`

WIP

## Testing in `kajabi-products`

WIP

## Related

[Sage-212](https://kajabi.atlassian.net/browse/SAGE-212)

2022-02-28 19:26 UTC, pixelflips approved these changes
LGTM! Left a few general comments, but non-blockers.

2022-02-28 19:26 UTC, pixelflips commented on docs/lib/sage_rails/app/views/sage_components/_sage_form_select.html.erb
> +  <label class="sage-select__label" for="<%= selectName %>"><%= label %></label>
This is another instance where we will need to note that the markup structure has changed in relation to SimpleForm within KP. There are quite a few instances when doing a quick search for `sage-select__field` in KP

2022-02-28 19:26 UTC, pixelflips commented on packages/sage-assets/lib/stylesheets/components/_form_select.scss
> +  @include sage-icon-base(down-small);
May be out of scope for these updates, but in the mocks, it appears the arrow flips up and down. Not a show-stopper, but might be worth noting for a follow-up.

2022-02-28 20:16 UTC, anechol commented on docs/lib/sage_rails/app/views/sage_components/_sage_form_select.html.erb
> +  <label class="sage-select__label" for="<%= selectName %>"><%= label %></label>
Thanks for this callout! I'll add that to the description.

2022-02-28 20:40 UTC, anechol commented on packages/sage-assets/lib/stylesheets/components/_form_select.scss
> +  @include sage-icon-base(down-small);
@pixelflips Just updated this. Should work as expected now.

2022-02-28 22:24 UTC, philschanely requested changes
Looking really good overall. Two small details to circle back to.

2022-02-28 22:24 UTC, philschanely commented on packages/sage-assets/lib/stylesheets/components/_form_select.scss
> +  @include sage-icon-base(down-small);
I'm not sure its meant to stay flipped when selected but only while the menu is open.

2022-02-28 22:24 UTC, philschanely commented on docs/lib/sage_rails/app/views/sage_components/_sage_form_select.html.erb
> +  <label class="sage-select__label" for="<%= selectName %>"><%= label %></label>
I believe the convention with variables in Rails is to use `snake_case`. Sorry to nitpick.

2022-03-01 17:10 UTC, anechol commented
> Looking really good overall. Two small details to circle back to.

@philschanely Thanks, I'll get these updated. Don't worry about nitpicking, I do want these little things pointed out. It's helpful!

2022-03-02 21:53 UTC, anechol commented
Created a follow-up ticket in Jira to handle the change to the icon being flipped. It's more involved and out of scope for this ticket than expected. All other visual changes should be in place.

2022-03-02 22:05 UTC, monicawheeler commented on packages/sage-assets/lib/stylesheets/components/_form_select.scss
> +    @include position(31%, sage-spacing(sm), unset, unset);
For this `31%` value and `41%` value on line 114, is it possible to represent this as a calculation within a variable? If not, could it be commented as to why it's written this way? Something like, "Percentage is hard-coded due to specific positioning needed within the input space."

2022-03-02 22:06 UTC, monicawheeler requested changes
Small item on magic numbers for the `.sage-select__arrow`

2022-03-03 00:54 UTC, monkeypox8 approved these changes
👍 LGTM, nice work!

2022-03-03 00:54 UTC, monkeypox8 commented on packages/sage-assets/lib/stylesheets/components/_form_select.scss
> +    .sage-form-field--error & {
Added one more [follow-up item,](https://kajabi.atlassian.net/browse/SAGE-337) as renaming the error class here will impact a few crucial areas:

```
app/javascript/common/components/DynamicSelect/DynamicSelect.jsx:
  31:       'sage-select--error': hasError,

app/views/admin/coupons/_form.html.erb:
  93:             <div class="sage-select<%= " sage-select--error" if coupon.errors[:currency].present? %>" data-js-select="true">

config/initializers/simple_form_sage.rb:
  65:   config.wrappers :sage_select, class: "sage-select", error_class: "sage-select--error", wrapper_html: { "data-js-select": true } do |b|
```

2022-03-03 19:21 UTC, anechol commented on packages/sage-assets/lib/stylesheets/components/_form_select.scss
> +    .sage-form-field--error & {
Thanks, I've added this to the description.

2022-03-03 19:25 UTC, monicawheeler commented on packages/sage-assets/lib/stylesheets/components/_form_select.scss
> +$-select-arrow-position: calc(100% - #{$-select-height});
🙌

2022-03-03 19:27 UTC, monicawheeler commented on docs/lib/sage_rails/app/views/sage_components/_sage_form_select.html.erb
> +  # Temporary variables here until refactor for 'name' is complete
```suggestion
  # Temporary variables here until refactor for 'name' is complete; see https://kajabi.atlassian.net/browse/SAGE-214
```

2022-03-03 19:51 UTC, monicawheeler commented on docs/lib/sage_rails/app/views/sage_components/_sage_form_select.html.erb
> +  # Temporary variables here until refactor for 'name' is complete
@anechol - just a minor consideration here

2022-03-03 19:51 UTC, monicawheeler approved these changes

2022-03-03 19:53 UTC, anechol commented on docs/lib/sage_rails/app/views/sage_components/_sage_form_select.html.erb
> +  # Temporary variables here until refactor for 'name' is complete
Added this in. Thanks!

2022-03-03 20:36 UTC, merged