[Sage-216] Radio, Checkbox - Foundations Update
Kajabi/sage-lib pull request #1212
Opened 2022-02-15 17:52 UTC by anechol

## Description

Updates Radio and Checkbox components.

### Radio
- Adjusts left margin of label to `12px`

### Checkbox
- Adjusts left margin of label to `12px`

## Screenshots

|  Before  |  After  |
|--------|--------|
WIP|WIP

## Testing in `sage-lib`

WIP

## Testing in `kajabi-products`

WIP

## Related

[Sage-216](https://kajabi.atlassian.net/browse/SAGE-216)

2022-02-17 22:36 UTC, philschanely approved these changes
Looking good here! 🙌

2022-02-17 22:56 UTC, pixelflips requested changes
This looks great. A couple of tiny nitpicks and one small thing I noticed that may not be related to these updates. 

The disabled/checked radio gets an outline applied on hover. The disabled/checked checkbox does not. Not sure which is actually correct.

![Screen Shot 2022-02-17 at 2 50 30 PM](https://user-images.githubusercontent.com/1175111/154584798-3786b029-5e66-4e15-9f42-cb805307e0e0.png)

2022-02-17 22:56 UTC, pixelflips commented on docs/app/views/examples/components/checkbox/_props.html.erb
> +</tr>
Nitpick: missing newline

2022-02-17 22:56 UTC, pixelflips commented on docs/app/views/examples/components/radio/_props.html.erb
> +</tr>
Nitpick: missing newline

2022-02-22 16:46 UTC, pixelflips approved these changes
👍🏼  LGTM! Great work. Thanks for resolving those minor issues!

2022-02-22 19:27 UTC, merged