Add Dot component
Kajabi/sage-lib pull request #1215
Opened 2022-02-17 02:36 UTC by philschanely

## Description

This PR adds a new component, `SageDot`, for adding a small colored dot distinctly into a layout or pattern, such as what is currently in the Legend and Statbox.

## Screenshots

<img width="842" alt="Screen Shot 2022-02-16 at 9 34 41 PM" src="https://user-images.githubusercontent.com/17955295/154393724-0ccb323e-be74-439e-9d85-b70a4a37bcfd.png">

## Testing in `sage-lib`

See Components > Dot and the same in React

## Testing in `kajabi-products`

1. (**N/A**) Adds new `SageDot` component.

2022-02-17 03:07 UTC, monicawheeler commented on packages/sage-react/lib/Dot/configs.js
> +export const DOT_COLORS = {
It appears that `grey` is missing here.

2022-02-17 03:10 UTC, monicawheeler requested changes
Looking great! A small request/possible change in the React side noted inline and also, a couple of questions:
* Is there a Figma file that can be added to the PRs description to verify design parity? 
* Is there a need for the other instances of "dot-like" components like you mentioned with Legend and StatBox? If not, is there deprecation considerations for `kp` to be noted for this?

2022-02-17 19:49 UTC, philschanely commented on docs/app/helpers/components_helper.rb
> +        figma_embed: nil, # TODO: We'll have a link for this in the new design system
@monicawheeler see comment here. This is a new "atom" that is needed for some product teams but it doesn't seem worth asking design to add it into Figma's 3.0 file at this time. Def on the list for the new system though.

If a comparable dot is still desired, see the dots in the StatBox component here https://www.figma.com/file/9Km09NjlZHYWsMP7EGT8tI/Sage-3-for-Admin?node-id=6999%3A22013

2022-02-17 19:52 UTC, philschanely commented on packages/sage-react/lib/Dot/configs.js
> +export const DOT_COLORS = {
Got it now; good catch!

2022-02-17 19:53 UTC, philschanely commented
@monicawheeler mind another look now? I've added a comment regarding the Figma spec and fixed the missing color.

2022-02-17 19:55 UTC, monicawheeler approved these changes
LGTM!

2022-02-17 20:29 UTC, QuintonJason commented on docs/app/helpers/components_helper.rb
> +        scss: "todo",
Can these values be updated to reflect on the status page?

2022-02-17 20:30 UTC, philschanely commented on docs/app/helpers/components_helper.rb
> +        scss: "todo",
Any `a11y` concerns for that item's status?

2022-02-17 20:46 UTC, QuintonJason commented on docs/app/helpers/components_helper.rb
> +        scss: "todo",
you added aria stuff so it looks completed

2022-02-17 21:38 UTC, philschanely commented on docs/app/helpers/components_helper.rb
> +        scss: "todo",
These are updated and ready for another look @QuintonJason .

2022-02-17 21:39 UTC, philschanely commented on docs/app/helpers/components_helper.rb
> +        figma_embed: nil, # TODO: We'll have a link for this in the new design system
Sorry to say there is no great spec for this to link in yet though the styling has been in the system nested in other components. I separated that out for distinct usage and we can def circle back in the redesign to get a spec and tighten this up.

2022-02-18 00:54 UTC, QuintonJason approved these changes

2022-02-18 01:00 UTC, merged