[SAGE-256] Nav/Nav Link and Sidebar - Foundations Update
Kajabi/sage-lib pull request #1226
Opened 2022-02-23 00:12 UTC by pixelflips

## Description
Foundational updates to nav/nav link and sidebar component with the following updates:

- Adjust colors and spacing of text
- Adjust colors and spacing focus/active states
- Add a border to the submenu section

Note this update does not include filled icons or updates to sidebar background colors (the sidebar should be updated in the Stage Color project). 

## Screenshots

|  Before  |  After  |
|--------|--------|
|![Screen Shot 2022-02-22 at 4 00 49 PM](https://user-images.githubusercontent.com/1175111/155240740-ef93653f-f2cc-40f8-8417-c28663a83aa6.png)|INCOMING...|

## Testing in `sage-lib`

- Navigate to [Sidebar](http://localhost:4000/pages/component/sidebar), [Nav](http://localhost:4000/pages/component/nav), and [Nav Link](http://localhost:4000/pages/component/nav_link)
- Verify updates match foundations [design mock](https://www.figma.com/file/sMbtLUHSt2vfKgKjyQ3052/%E2%9A%A0%EF%B8%8F-%5BDO-NOT-USE-WIP%5D-Sage-Update?node-id=479%3A45769)

## Testing in `kajabi-products`
1. (**LOW**) Foundational updates to sidebar, nav, and nav link styling to match the new design updates.

## Related
https://kajabi.atlassian.net/browse/SAGE-256

2022-02-23 17:56 UTC, anechol requested changes
Looking very good and clean. Just a few minor nitpicks I noticed:

- The space between the icon and text seems to be about 14px. When you reference Figma files, do you go by absolute measurements on Figma or just eyeball it? I'm mostly asking because Figma tends to be weird about spacing with regards to text and sometimes I'm unsure of which one I should be following. 😅 
- The font weight here for text should be `semibold`. I should have made an earlier mention about this in Slack, but for some reason this font has no semibold font, instead it's marked as `medium'. The actual `medium` font weight is marked as Book in Figma. Sorry for the confusion!
- The focus outline is a little off from the border radius.<img width="691" alt="Screen Shot 2022-02-23 at 11 21 29 AM" src="https://user-images.githubusercontent.com/14791307/155377584-28fb29ac-d2fe-48f1-b251-b4a792f50b70.png">
- Extremely nitpicky here but the padding between the border and the sub menu item is about 24px. Would this be a similar issue as above with the text spacing?

2022-02-23 18:21 UTC, pixelflips commented
> Looking very good and clean. Just a few minor nitpicks I noticed:
> 
> * The space between the icon and text seems to be about 14px. When you reference Figma files, do you go by absolute measurements on Figma or just eyeball it? I'm mostly asking because Figma tends to be weird about spacing with regards to text and sometimes I'm unsure of which one I should be following. 😅

I definitely use the Figma file and also Visbug in the browser. Just missed that one. Great eye!

> * The font weight here for text should be `semibold`. I should have made an earlier mention about this in Slack, but for some reason this font has no semibold font, instead it's marked as `medium'. The actual `medium` font weight is marked as Book in Figma. Sorry for the confusion!

Mind pinging me on this one? Not fully understanding.

> * The focus outline is a little off from the border radius.<img alt="Screen Shot 2022-02-23 at 11 21 29 AM" width="691" src="https://user-images.githubusercontent.com/14791307/155377584-28fb29ac-d2fe-48f1-b251-b4a792f50b70.png">

Ha! Missed this one as well due to lighter shades of grey and my non-hi-res monitor. Should be good now.

> * Extremely nitpicky here but the padding between the border and the sub menu item is about 24px. Would this be a similar issue as above with the text spacing?

Again great eye! Just another oversight. This is why I love reviews!!

2022-02-23 21:03 UTC, anechol approved these changes
Awesome work!

2022-02-24 00:20 UTC, monkeypox8 approved these changes
👍 LGTM, great work! Added a couple of non-blocking comments.

2022-02-24 00:37 UTC, pixelflips commented on packages/sage-assets/lib/stylesheets/components/_nav.scss
> +  border-radius: rem(10px);
@monkeypox8 - I'll confirm. Stay tuned.

2022-02-24 00:37 UTC, pixelflips commented on packages/sage-assets/lib/stylesheets/components/_nav.scss
> +  margin-left: rem(25.5px);
@monkeypox8 good call. I'll adjust.

2022-02-24 18:17 UTC, pixelflips commented on packages/sage-assets/lib/stylesheets/components/_nav.scss
> +  border-radius: rem(10px);
@monkeypox8 So it looks like there is a new 10px radius that's been added. I updated this one to sage-border() instead of the rem().

2022-02-24 19:13 UTC, merged