[SAGE-257]: Breadcrumbs - Foundations Update
Kajabi/sage-lib pull request #1236
Opened 2022-02-25 22:52 UTC by pixelflips

## Description
Foundational updates to breadcrumbs component with the following updates:

- Color adjustments
- Spacing adjustments
- Font size updates
- :hover, :active, :focus updates

## Screenshots

|  Before  |  After  |
|--------|--------|
|![Screen Shot 2022-02-25 at 2 39 04 PM](https://user-images.githubusercontent.com/1175111/155813462-37000b6a-69b2-4582-93db-00de489d1d47.png)|![Screen Shot 2022-02-25 at 2 38 34 PM](https://user-images.githubusercontent.com/1175111/155813493-ea6ee0ed-41b9-4271-8d08-f127de1d74da.png)|

## Testing in `sage-lib`
- Navigate to http://localhost:4000/pages/component/breadcrumbs
- Verify updates match new foundations design mock.

## Testing in `kajabi-products`
1. (**LOW***) Foundational updates to the breadcrumbs styling to match the new foundational design updates.

## Related
https://kajabi.atlassian.net/browse/SAGE-257

2022-02-28 18:17 UTC, pixelflips commented on packages/sage-assets/lib/stylesheets/components/_breadcrumbs.scss
> +      margin: 0 rem(12px);
there is currently no sage-spacing for 12px.

2022-02-28 18:22 UTC, pixelflips commented on packages/sage-assets/lib/stylesheets/components/_breadcrumbs.scss
> +    border-radius: rem(6px); // verify w/ design (is this new)
there is currently no sage-border() for 6px. Confirming with design if this is a one-off or if we should add.

2022-02-28 18:28 UTC, pixelflips commented on packages/sage-assets/lib/stylesheets/components/_breadcrumbs.scss
> +    border-radius: rem(6px);
there is currently no sage-border() for 6px. Confirming with design if this is a one-off or if we should add to tokens. Will need to work out naming...

2022-03-02 22:04 UTC, anechol requested changes
Looking good! Just a couple of small changes.

2022-03-02 22:04 UTC, anechol commented on packages/sage-assets/lib/stylesheets/components/_breadcrumbs.scss
> +  padding: sage-spacing(3xs) sage-spacing(xs);
Should the padding here be `4px 8px` instead?

2022-03-02 22:10 UTC, pixelflips commented on packages/sage-assets/lib/stylesheets/components/_breadcrumbs.scss
> +  padding: sage-spacing(3xs) sage-spacing(xs);
@anechol if we want the overall size to match the mock it needs to be smaller. The height is 28px in the mock and would increase to 32px if we use that padding. Happy to change, but let me know what you think?

2022-03-02 22:14 UTC, pixelflips commented on packages/sage-assets/lib/stylesheets/components/_breadcrumbs.scss
> +  font-size: sage-font-size(body-sm);
@anechol done.

2022-03-02 22:31 UTC, anechol commented on packages/sage-assets/lib/stylesheets/components/_breadcrumbs.scss
> +  padding: sage-spacing(3xs) sage-spacing(xs);
Ahh this is one of those weird Figma things. Would be helpful to have some consensus around how to approach this. This might be a better question for Design, but I'm fine with leaving it for now.

2022-03-02 22:33 UTC, anechol approved these changes
🚀

2022-03-02 22:51 UTC, merged