[SAGE-345] add progress bar to react
Kajabi/sage-lib pull request #1260
Opened 2022-03-09 02:35 UTC by QuintonJason

## Description

- [ ] add progress bar react version

## Screenshots

|  Before  |  After  |
|--------|--------|
|||

## Testing in `sage-lib`

## Testing in `kajabi-products`

1. (**LOW/MEDIUM/HIGH/BREAKING**) Description of the change and its impact with QA as the audience.
   - [ ] One more examples of the component in use to either test the change or verify the change has not had adverse effects.

## Related

Closes [SAGE-345](https://kajabi.atlassian.net/browse/SAGE-345)

2022-03-09 21:56 UTC, pixelflips approved these changes

2022-03-09 21:58 UTC, pixelflips requested changes
The code looks good but seems the empty spec file is causing failures.

`packages/sage-react/lib/ProgressBar/ProgressBar.spec.jsx`

It looks like there is somewhat of a template we're using in other files. 

See `packages/sage-react/lib/DataCard/DataCard.spec.jsx` or `packages/sage-react/lib/Dot/Dot.spec.jsx` as examples

2022-03-10 20:59 UTC, QuintonJason commented
> The code looks good but seems the empty spec file is causing failures.
> 
> `packages/sage-react/lib/ProgressBar/ProgressBar.spec.jsx`
> 
> It looks like there is somewhat of a template we're using in other files.
> 
> See `packages/sage-react/lib/DataCard/DataCard.spec.jsx` or `packages/sage-react/lib/Dot/Dot.spec.jsx` as examples

@pixelflips thanks for the update. pushed a fix

2022-03-10 21:01 UTC, pixelflips approved these changes
👍

2022-03-10 21:56 UTC, merged