[SAGE-352] Grid add fixed column width
Kajabi/sage-lib pull request #1265
Opened 2022-03-14 15:34 UTC by QuintonJason

## Description

- [x] add ability for the Grid to have a fixed width column. The parent grid should allow for the natural width of the children to determine the width

## Screenshots

![variableWidth](https://user-images.githubusercontent.com/1241836/158205648-454ec296-9e1b-4e17-bffd-8906ef9f7bb0.gif)

## Testing in `sage-lib`

Go the Grid views and resize the browser to verify that `Variable Width` variation works as expected:
- [Rails](http://localhost:4000/pages/patterns/grid)
- [React](http://localhost:4100/?path=/story/sage-grid--variable-width)

## Testing in `kajabi-products`

1. (**LOW**) Adds new `Grid` property. Has no affect in the app

## Related

Closes [SAGE-352](https://kajabi.atlassian.net/browse/SAGE-352)

2022-03-14 15:49 UTC, pixelflips requested changes
A couple of nitpicks to address but overall looking good so far.

2022-03-14 15:49 UTC, pixelflips commented on packages/sage-react/lib/mocks/product-creation-wizard/components/Root.jsx
> +            <Grid.Col variableWidth='225px'>
Linter is yelling here.

2022-03-14 15:50 UTC, QuintonJason commented on packages/sage-react/lib/mocks/product-creation-wizard/components/Root.jsx
> +            <Grid.Col variableWidth='225px'>
@philschanely Hey hey. I like `fixedWidth`. I did about 4 find replaces struggling to find something. You suggestion is solid. The part being passed in is wrong. I need to update. That value should be a `Boolean`

2022-03-14 15:51 UTC, QuintonJason commented on docs/lib/sage_rails/app/sage_components/sage_grid_col.rb
> +    variableWidth: [:optional, TrueClass]
Great callout! Switching between rails and react 🙃

2022-03-14 15:56 UTC, QuintonJason commented on packages/sage-react/lib/mocks/product-creation-wizard/components/Root.jsx
> +            <Grid.Col variableWidth='225px'>
@philschanely pushed

2022-03-14 16:11 UTC, pixelflips approved these changes
LGTM and behaving as expected. Nice work! 👍🏼

2022-03-14 16:11 UTC, pixelflips commented on packages/sage-assets/lib/stylesheets/layout/_grid.scss
> +  max-width: none;
TIL max-width can be none!

2022-05-02 19:08 UTC, QuintonJason commented
Closing in favor of this PR, #1375

2022-05-02 19:08 UTC, closed without merging