[SAGE-390] Upload Card foundations update
Kajabi/sage-lib pull request #1296
Opened 2022-03-30 01:09 UTC by QuintonJason

## Description

- [x] update file upload to align with foundations styles

## Screenshots

|  Before  |  After  |
|--------|--------|
|![Screen Shot 2022-03-29 at 8 06 33 PM](https://user-images.githubusercontent.com/1241836/160730762-3f188155-8518-48af-a525-28645ebb0676.png)|![Screen Shot 2022-03-29 at 8 06 12 PM](https://user-images.githubusercontent.com/1241836/160730773-8468e518-9089-4c62-8310-5f038a78b678.png)|

## Testing in `sage-lib`

Visit the Upload Card views and verify alignment with the foundations styles:
- [Rails](http://localhost:4000/pages/component/upload_card)
- [React](http://localhost:4100/?path=/docs/sage-uploadcard--default)

## Testing in `kajabi-products`

1. (**LOW**) Minor visual style update to Upload Card component.

## Related

Closes [SAGE-390](https://kajabi.atlassian.net/browse/SAGE-390)

2022-03-30 17:37 UTC, pixelflips requested changes
I think the color for the `.sage-upload-card__subtext` is supposed to be Grey/600. Also seems the down arrow on the upload/action button was removed and the copy was adjusted. Not entirely sure "Click to upload" is the greatest CTA text though.

2022-03-30 21:33 UTC, anechol requested changes
Just a couple things to update if possible:
- Can we update the icon size to `24px`? That's about the closest the Figma design has currently
- Can we update the button font size to be 16px? Would that require an update to buttons overall?

And one question: is there a reasoning behind using SVGs for our dotted borders over the CSS property?

Other than that, good update work!!

2022-03-30 21:33 UTC, anechol commented on packages/sage-assets/lib/stylesheets/components/_upload_card.scss
>      @extend %t-sage-body-small;
The design file doesn't explicitly say this, but I think the subtexts are now supposed to be a font weight of Book (Medium).

2022-03-30 21:41 UTC, QuintonJason commented
> * Can we update the icon size to `24px`? That's about the closest the Figma design has currently
Can do

> * Can we update the button font size to be 16px? Would that require an update to buttons overall?
That would need to happen in a button update as their base font size is rendering at `16px` 
> And one question: is there a reasoning behind using SVGs for our dotted borders over the CSS property?
It's because the design is using a custom `dotted` border. There currently no way to customized the length of the dash

2022-03-30 21:50 UTC, QuintonJason commented
> I think the color for the `.sage-upload-card__subtext` is supposed to be Grey/600. Also seems the down arrow on the upload/action button was removed and the copy was adjusted. Not entirely sure "Click to upload" is the greatest CTA text though.

Updated the color, but I'll leave the copy since that prop can be set on the component

2022-03-30 22:38 UTC, pixelflips approved these changes
Besides the linter yelling, LGTM! 👍🏼

2022-03-31 14:33 UTC, anechol approved these changes
:shipit:

2022-03-31 19:28 UTC, merged