[SAGE-294] Search foundations update
Kajabi/sage-lib pull request #1298
Opened 2022-03-30 14:41 UTC by QuintonJason

## Description

- [x] align search component to foundations 

## Screenshots

|  Before  |  After  |
|--------|--------|
|![search-before-before](https://user-images.githubusercontent.com/1241836/160861233-824246f1-4f7d-42ab-9793-6dda33ce01f0.gif)|![search-after](https://user-images.githubusercontent.com/1241836/160861209-4c0b66a8-702f-4a50-b585-f46ddc13c14a.gif)|

## Testing in `sage-lib`

Visit the search component views and verify alignment with foundations spec:
- [Rails](http://localhost:4000/pages/component/search)
- [React](http://localhost:4100/?path=/story/sage-search--default)

## Testing in `kajabi-products`
A part of the foundations Epic PR

## Related

Closes [SAGE-294](url)

2022-03-30 17:37 UTC, monicawheeler commented on packages/sage-assets/lib/stylesheets/components/_search.scss
> +    color: sage-color(charcoal, 400);
Looks like this value should be:

```suggestion
    color: sage-color(grey, 600);
```

2022-03-30 17:37 UTC, monicawheeler commented on packages/sage-assets/lib/stylesheets/components/_search.scss
> +      // box-shadow: map-get($sage-toolbar-button-borders, focus);
Do we need to keep this comment?

2022-03-30 17:38 UTC, monicawheeler commented on packages/sage-assets/lib/stylesheets/components/_search.scss
> +    // box-shadow: none;
Also, should this comment be removed?

2022-03-30 17:38 UTC, monicawheeler requested changes
A couple of notes to review!

2022-03-31 15:42 UTC, anechol requested changes
Nice work! Just a few changes:
- Can we update the disabled font color to `Grey 600`. The icon looks like it should be about the same color but it's listed as `Charcoal 400` in the Design files. Judging by the color system, it does seem to line up with what the current Grey color should be so the icon might be fine as is.
- You can barely see this, but can we fix the border spacing here to match with the background?
<img width="540" alt="Screen Shot 2022-03-31 at 10 32 07 AM" src="https://user-images.githubusercontent.com/14791307/161093399-16061eb7-df76-43ce-a654-68581fa5e57b.png">

General question: 
I was under the impression that we were deprecating floating labels? Is this no longer the case?

2022-04-01 20:58 UTC, anechol approved these changes
🚀

2022-04-01 21:08 UTC, merged