[Sage-369] Modal - Content Scrolling Prop
Kajabi/sage-lib pull request #1318
Opened 2022-04-11 16:27 UTC by anechol

## Description

Adds `allow_scroll`/`allowScroll` prop to Rails and React to allow modal content to scroll.

## Screenshots

https://user-images.githubusercontent.com/14791307/162787300-1eab1d3c-316d-4f04-90e2-5623957995b8.mov

## Testing in `sage-lib`

- View [Modal](http://localhost:4000/pages/component/modal)
- Add extra body content and `allow_scroll` prop
- Check that body content scrolls as necessary.

## Testing in `kajabi-products`

(LOW) Adds `allow_scroll`/`allowScroll` prop to Rails and React to allow modal content to scroll. Scrolling is guarded behind an opt-in prop, so modals across the app will not be affected.

## Related

[Sage-369](https://kajabi.atlassian.net/browse/SAGE-369)

2022-04-11 16:58 UTC, anechol commented
Hey @philschanely, I would definitely love your input here. This should give Manage the flexibility they're expecting without affecting other modals across the app. That being said, I've had some conversations with @QuintonJason about Modals that left me wondering if we should create a follow-up ticket to refactor the component to fix clipping issues with other components like Dropdown.

2022-04-11 17:48 UTC, QuintonJason commented on packages/sage-assets/lib/stylesheets/components/_modal.scss
> +    padding: 8px 2px;
Can these be updated to use the `sage-spacing()` values?

2022-04-11 17:52 UTC, QuintonJason commented
Is it possible to add a Scrollableable Content modal demo / button with a long text var for the overflow content?

2022-04-12 16:43 UTC, monkeypox8 approved these changes
👍 LGTM!

2022-04-12 21:04 UTC, philschanely requested changes
Definitely on the desired track here. I've left some change requests in terms of CSS organization. LMK if I can assist or clarify.

2022-04-12 21:04 UTC, philschanely commented on packages/sage-assets/lib/stylesheets/components/_modal.scss
> +  .sage-modal__container,
For these nested selectors, precedent might suggest that we place these under the other styles for `sage-modal__container like this:

```scss
.sage-modal__container {
  // other existing styles
  
  .sage-modal--scrollable &,
  .sage-modal--scrollable & > .simple_form {
    // styles here
  }
  
  // etc...
}
```

Aim being, as much as practical, to have a given element's styles all consolidated in one place so we can more easily see what is affecting it together.

2022-04-12 21:04 UTC, philschanely commented on packages/sage-assets/lib/stylesheets/components/_modal.scss
> +  .sage-modal__container,
Admittedly, it gets thicker when we add the `.simple_form` layer, but I think here's its grouped for that tangential case where it's nested within our modal.

2022-04-12 21:04 UTC, philschanely commented on packages/sage-assets/lib/stylesheets/components/_modal.scss
> +  .sage-modal__container .sage-modal__content,
Given comment above, these might should split up with `__content` moving to group with that element in this stylesheet, but the simple form might should go with the `__container`. Its a grey area for sure since its technically outside of our system.

2022-04-12 21:37 UTC, anechol commented on packages/sage-assets/lib/stylesheets/components/_modal.scss
> +    overflow: auto;
Thanks for mentioning this, I didn't know we had this mixin.

2022-04-12 21:37 UTC, anechol commented on packages/sage-assets/lib/stylesheets/components/_modal.scss
> +  .sage-modal__container .sage-modal__content,
Thanks for all the feedback, I've made some changes.

2022-04-12 23:26 UTC, QuintonJason requested changes
The `margin-top` from the `.sage-modal__content` is cutting into the scrollable area. Can we move the spacing from the parent to the first child?

Something like:
```
margin-top: 0;

& > :first-child {
  margin-top: sage-spacing(xs);
}
```

2022-04-13 17:03 UTC, QuintonJason approved these changes

2022-04-15 14:51 UTC, merged