[SAGE-392] Foundations form input, textarea, select updates
Kajabi/sage-lib pull request #1323
Opened 2022-04-12 21:21 UTC by QuintonJason

## Description

- [x] update form input to latest sage specs
- [x] update form textarea to latest sage specs
- [x] update form select to latest sage specs

## Screenshots

#### `FormInput`
|  Before  |  After  |
|--------|--------|
|![Screen Shot 2022-04-12 at 4 18 34 PM](https://user-images.githubusercontent.com/1241836/163056397-3fdd7047-5c34-42c0-bc83-c8acf74cbd6c.png)|![Screen Shot 2022-04-12 at 4 11 16 PM](https://user-images.githubusercontent.com/1241836/163055744-9a227520-ac06-4bda-867d-7544ac1f3e64.png)|

#### `FormTextarea`
|  Before  |  After  |
|--------|--------|
|![Screen Shot 2022-04-12 at 4 18 48 PM](https://user-images.githubusercontent.com/1241836/163056422-20389be7-d998-441c-95f9-ae0641f15f24.png)|![Screen Shot 2022-04-12 at 4 11 41 PM](https://user-images.githubusercontent.com/1241836/163055759-7356ff53-2659-4a49-9a73-e438294cb4f2.png)|

#### `FormSelect`
|  Before  |  After  |
|--------|--------|
|![Screen Shot 2022-04-12 at 4 18 58 PM](https://user-images.githubusercontent.com/1241836/163056441-1c7d0167-a9b2-4075-995b-a0d61350847f.png)|![Screen Shot 2022-04-12 at 4 11 55 PM](https://user-images.githubusercontent.com/1241836/163055813-f5a0c522-70c5-4743-8a9f-db2895f40d77.png)|

## Testing in `sage-lib`

Verify that the following components are aligned with the latest sage specs:
- Rails
  - [FormInput](http://localhost:4000/pages/component/form_input)
  - [FormTextarea](http://localhost:4000/pages/component/form_textarea)
  - [FormSelect](http://localhost:4000/pages/component/form_select)
- React
  - [FormInput](http://localhost:4100/?path=/story/sage-input--default)
  - [FormTextarea](http://localhost:4100/?path=/story/sage-textarea--default)
  - [FormSelect](http://localhost:4100/?path=/story/sage-select--default)

## Related

Closes [SAGE-392](https://kajabi.atlassian.net/browse/SAGE-392)

2022-04-15 01:26 UTC, monkeypox8 commented on packages/sage-assets/lib/stylesheets/components/_form_textarea.scss
>    @include sage-form-field;
Textarea looks good, but I'm wondering if we'd want to update the input field vertical padding to `0.5rem` to match the spec, since the `line-height` should take care of the vertical alignment, and the placeholder abs positioning is no longer a concern:

![input-padding](https://user-images.githubusercontent.com/816579/163502671-e6e781de-1859-4f7f-8eec-22e655927d30.png)

2022-04-15 17:39 UTC, anechol requested changes
Just one change mentioned and then we're good here.

2022-04-15 17:39 UTC, anechol commented on packages/sage-assets/lib/stylesheets/components/_form_textarea.scss
>    @include sage-form-field;
Agree here.

2022-04-15 18:22 UTC, anechol commented
Just an update: Border error state focus styles have been changed back to what they were originally.

2022-04-15 18:25 UTC, monkeypox8 requested changes
Focus outline style on input errors have been updated, so we'll need a change. The rest looks great.

2022-04-18 20:48 UTC, philschanely approved these changes

2022-04-18 21:45 UTC, monicawheeler approved these changes

2022-04-18 21:50 UTC, anechol approved these changes
Awesome work!

2022-04-18 21:55 UTC, monkeypox8 approved these changes
👍 LGTM!

2022-04-18 22:00 UTC, pixelflips approved these changes
LGTM! We'll need to create a follow-up ticket (if you haven't already) to add the new `__field-wrapper` parent to the SimpleForm inputs/selects that are currently using the `sage-select__field` class.

2022-04-18 23:11 UTC, merged