[SAGE-441] Nav and NavLink foundations
Kajabi/sage-lib pull request #1327
Opened 2022-04-13 18:34 UTC by QuintonJason

## Description

## Screenshots

|  Before  |  After  |
|--------|--------|
|||

## Testing in `sage-lib`

## Related

Closes [SAGE-441](https://kajabi.atlassian.net/browse/SAGE-441)

2022-04-15 19:12 UTC, anechol requested changes
Just a couple changes. And there's a linting issue that causing some style to not come through.

2022-04-15 19:12 UTC, anechol commented on packages/sage-assets/lib/stylesheets/components/_nav.scss
> +  padding: sage-spacing(xs) rem(10px);
Can we update this to `10px 12px`?

2022-04-15 19:12 UTC, anechol commented on packages/sage-assets/lib/stylesheets/components/_nav.scss
> +  padding-left: sage-spacing();
Can we add this padding to the `.sage-nav__list--sub` class as well?

2022-04-18 20:27 UTC, monicawheeler approved these changes

2022-04-18 20:49 UTC, philschanely approved these changes

2022-04-18 22:00 UTC, merged