Sage 407 pjs list component
Kajabi/sage-lib pull request #1334
Opened 2022-04-16 20:14 UTC by philschanely

## Description

This PR adds the new List component that will be used for more compositional lists and eventually to replace Sortable, Catalog Item and 

- [x] Add in Rails
- [x] Add Reveal utility
- [ ] Add in React

## Screenshots

![Screen Shot 2022-04-16 at 4 12 52 PM](https://user-images.githubusercontent.com/17955295/163690014-d1cf9e3a-767a-4aeb-8781-547f240c4c06.png)

## Testing in `sage-lib`

- see http://localhost:4000/pages/component/list
- Storybook coming soon

## Testing in `kajabi-products`

1. (N/A) New List component

## Related

https://kajabi.atlassian.net/browse/SAGE-407

2022-04-18 20:14 UTC, monicawheeler commented on docs/app/views/examples/components/list/_preview.html.erb
> +
Seems to be an extra space here. Was that intentional?

2022-04-18 20:15 UTC, monicawheeler commented on docs/app/views/examples/components/list/_preview.html.erb
> +SageList is implimented most simply by passing the desired contents for the items through the `SageList` `items` property.
```suggestion
SageList is implemented most simply by passing the desired contents for the items through the `SageList` `items` property.
```

2022-04-18 20:21 UTC, monicawheeler commented on docs/lib/sage_rails/app/views/sage_components/_sage_list.html.erb
> +<div
What are your thoughts around defaulting to a `ul` with an option to set an `ol` since this is called a List component?

2022-04-18 20:22 UTC, monicawheeler commented on packages/sage-assets/lib/stylesheets/dictionary/_tokens.scss
> +
An extra space seems to have been added here 🤔

2022-04-18 20:24 UTC, monicawheeler requested changes
Looks great! A couple of small notes up for your consideration.

2022-04-20 20:55 UTC, philschanely commented on docs/lib/sage_rails/app/views/sage_components/_sage_list.html.erb
> +<div
Love it. Will put in revised PR

2022-04-20 21:14 UTC, closed without merging