[SAGE-387] Description List foundations update
Kajabi/sage-lib pull request #1348
Opened 2022-04-19 23:16 UTC by QuintonJason

## Description

- [x] update position of the actions
- [x] update `grid-template-columns` and vars to account for going from 3 columns to 2, related to custom title and action widths

## Screenshots

|  Before  |  After  |
|--------|--------|
|<img width="743" alt="Screen Shot 2022-04-19 at 6 05 22 PM" src="https://user-images.githubusercontent.com/1241836/164116133-5e367a7e-67eb-4311-92cb-80f670a43688.png">|<img width="744" alt="Screen Shot 2022-04-19 at 6 12 16 PM" src="https://user-images.githubusercontent.com/1241836/164116141-b3879c28-6359-49da-a8bc-d41a1d67a1a2.png">|

## Testing in `sage-lib`

Visit the description list view and verify alignment with the foundations spec:
- [Rails](http://localhost:4000/pages/component/description)
- [React](http://localhost:4100/?path=/story/sage-description--multiple-items-with-action-button)

## Related

Closes [SAGE-387](https://kajabi.atlassian.net/browse/SAGE-387)

2022-04-19 23:38 UTC, pixelflips approved these changes
Overall LGTM! 👍🏼  Nice work!

As a side note the arrow-only actions seem a bit out of place in the docs examples (due to new placement), but not a show-stopper for this PR.

2022-04-19 23:52 UTC, monkeypox8 requested changes
One quick update on the parent element, should be good to go otherwise

2022-04-19 23:52 UTC, monkeypox8 commented on docs/lib/sage_rails/app/views/sage_components/themes/next/_sage_description.html.erb
> +    <div
Can we make this a `dl` rather than a `div`?

2022-04-20 00:11 UTC, monkeypox8 commented on docs/lib/sage_rails/app/views/sage_components/themes/next/_sage_description.html.erb
> +    <div
Marking this as resolved because I was mistaken in thinking `div` to be an invalid child of a `dl`, but this is not the case:
> In order to annotate groups with [microdata](https://html.spec.whatwg.org/multipage/microdata.html#microdata) attributes, or other global attributes that apply to whole groups, or just for styling purposes, each group in a [dl](https://html.spec.whatwg.org/multipage/grouping-content.html#the-dl-element) element can be wrapped in a [div](https://html.spec.whatwg.org/multipage/grouping-content.html#the-div-element) element. This does not change the semantics of the [dl](https://html.spec.whatwg.org/multipage/grouping-content.html#the-dl-element) element.

2022-04-20 00:56 UTC, monkeypox8 approved these changes
👍 LGTM! I'm uncertain whether the legacy components should also be updated to reflect the updated semantics but that can be handled in a follow-up if needed.

/cc @monicawheeler

2022-04-20 01:14 UTC, merged