docs(tabs): allows selected tab to be bookmarked
Kajabi/sage-lib pull request #1366
Opened 2022-04-25 23:26 UTC by ju-Skinner

Having the ability to bookmark a component with the selected tab.

re #SAGE-78

## Description
Allows the customer to the ability to bookmark a page with the current active tab. 

## Video

## Testing in `sage-lib`

## Testing in `kajabi-products`

2022-04-25 23:37 UTC, ju-Skinner commented on docs/app/views/examples/components/_component.html.erb
> +        permalink: true,
This enables the functionality on all Components pages, since this is nothing more than a reusable rails partial. So if you were to pull and run locally, it should work on any component in the list.

2022-04-25 23:39 UTC, ju-Skinner commented on packages/sage-system/lib/tabs.js
> +        history.pushState({id: target, source: 'web'}, target, [location.origin, location.pathname, '?', params.toString()].join(''));
Need to work out some kinks when navigating forward and back. You may notice that the reloading of the page will NOT occur.

2022-04-27 22:47 UTC, ju-Skinner commented on docs/app/views/examples/components/themes/legacy/tabs/_props.html.erb
> +-->
Hiding this until we figure out a good UX for Kajabi Products.

2022-04-27 22:49 UTC, ju-Skinner commented on packages/sage-system/lib/tabs.js
> +        });
This listens for changes to the History State.

2022-04-27 22:50 UTC, ju-Skinner commented on packages/sage-system/lib/tabs.js
> +    }
This is the main functionality.

2022-04-28 16:03 UTC, pixelflips approved these changes
🔥 LGTM! This is a great update, awesome work!

2022-04-29 19:21 UTC, ju-Skinner commented
If you are here again, this has been refactored to hook into the Tab changed event that is now exposed.

2022-04-29 19:22 UTC, ju-Skinner commented on packages/sage-system/lib/tabs.js
>    }
This now allows our customers to add an eventListener on the tabs. See [here](https://github.com/Kajabi/sage-lib/pull/1366/files#diff-0928f9ff40198b124c0d6035ff457afa8d11a8e023058bf4661bd6648281f81fR29-R34) for a reference

2022-04-29 19:47 UTC, pixelflips approved these changes

2022-05-02 14:28 UTC, philschanely approved these changes
One optional suggestion to hone a little more, but super excited about this. Well done! 🙌

2022-05-02 14:28 UTC, philschanely commented on docs/lib/sage_rails/app/sage_components/sage_tabs.rb
> +    permalink: [:optional, TrueClass], # For Docs site use only.
Did this end up being used only as a hook in the docs site? If so, I wonder if something like a custom class, id, or data- attribute used in local implementation might be better? Having this prop seems to suggest some built-in functionality that may not be as relevant anymore? Open to whatever you think but wanted to bring it up just in case its of interest to remove after all.

2022-05-02 15:16 UTC, QuintonJason requested changes
When I copy the URL for the `Code` tab and open in a new one, it opens the `Preview` tab

2022-05-02 15:34 UTC, ju-Skinner commented on docs/lib/sage_rails/app/sage_components/sage_tabs.rb
> +    permalink: [:optional, TrueClass], # For Docs site use only.
@philschanely we discussed previously that we would put a comment for now to  make lurkers aware that it's for internal Docs use. If we discover that this **will not** be something that the Devs may not wish to use, then we can go with just adding the data-attribute in the [docs/app/views/examples/components/_component.html.erb](https://github.com/Kajabi/sage-lib/pull/1366/files/43a593432c0e74c9665bbfe5f89afa2f8ee657fb#diff-9022d274bdc2073b3878a56ddc2620952a39945be74c307d4ea0da29a4a7eec5) file.

2022-05-02 16:36 UTC, ju-Skinner commented on packages/sage-system/lib/tabs.js
> +      }
@QuintonJason This was the missing piece that I forgot to add back in from the refactor.

2022-05-02 17:43 UTC, QuintonJason reviewed
Looks and work great!

2022-05-02 17:44 UTC, QuintonJason approved these changes

2022-05-03 18:15 UTC, merged