[SAGE-493] Add generic `.sage-col` when only no column size is specified
Kajabi/sage-lib pull request #1371
Opened 2022-04-27 19:50 UTC by QuintonJason

## Description

- [x] Add generic `.sage-col` when no column size is specified

## Screenshots

|  Before  |  After  |
|--------|--------|
|![Screen Shot 2022-04-27 at 8 51 43 AM](https://user-images.githubusercontent.com/1241836/165616979-0dc39eaf-e1de-4607-945c-b6e094f12b0b.png)|![Screen Shot 2022-04-27 at 1 42 21 PM](https://user-images.githubusercontent.com/1241836/165617100-511f8d28-4075-4d53-b07b-e93115892133.png)|

## Testing in `sage-lib`

**No visual regression**
Go the the Grid views and verify that the `.sage-col` class only shows when no `size`, `small`, `medium`, or `large` prop is set

## Testing in `kajabi-products`

1. (**HIGH**) Updates classes on the Grid component. Requires QA as this is a high usage component.

## Related

2022-04-27 20:09 UTC, philschanely commented on docs/lib/sage_rails/app/views/sage_components/themes/legacy/_sage_grid_col.html.erb
> +  <%= "sage-col" if !has_infix -%>
I'm unfamiliar with this term. What does it mean? 😄

2022-04-27 20:16 UTC, ju-Skinner requested changes
Requesting changes for the code in the `erb` files for `component.size`. See comments below.

2022-04-27 20:16 UTC, ju-Skinner commented on docs/lib/sage_rails/app/views/sage_components/themes/legacy/_sage_grid_col.html.erb
> +  <%= "sage-col--#{component.breakpoint}-#{component.size}" if component.breakpoint -%>
I would add the second check to your if condition `&& component.size`, since there is a dependency on it.

2022-04-27 20:16 UTC, ju-Skinner commented on docs/lib/sage_rails/app/views/sage_components/themes/next/_sage_grid_col.html.erb
> +  <%= "sage-col--#{component.breakpoint}-#{component.size}" if component.breakpoint -%>
Same as previous comment.

2022-04-27 20:16 UTC, ju-Skinner commented on packages/sage-react/lib/themes/legacy/Grid/GridCol.jsx
> +      'sage-col': !hasInfix,
This is more for clarity...the only time this would ever equate to `true` would be if all values are `null` .

2022-04-27 20:35 UTC, QuintonJason commented on packages/sage-react/lib/themes/legacy/Grid/GridCol.jsx
> +      'sage-col': !hasInfix,
That's correct. Did you have a recommendation that could provide more clarity?

2022-04-27 21:03 UTC, ju-Skinner commented on packages/sage-react/lib/themes/legacy/Grid/GridCol.jsx
> +      'sage-col': !hasInfix,
@QuintonJason I believe it's ok as it is.

2022-04-27 21:03 UTC, ju-Skinner approved these changes
Great job.

2022-05-02 13:48 UTC, QuintonJason commented on docs/lib/sage_rails/app/views/sage_components/themes/legacy/_sage_grid_col.html.erb
> +  <%= "sage-col" if !has_infix -%>
@philschanely Sorry didn't see this but need to call attention to it. From bootstrap to google material design, that's the variable that represent the value string of the breakpoints; like `sm` or `lg` for the column class generation loop. They may have different loops and what they are dependent on but that value is always represented that way.

2022-05-03 18:21 UTC, merged