[SAGE-316] Banner react variant
Kajabi/sage-lib pull request #1372
Opened 2022-04-27 20:24 UTC by QuintonJason

## Description

## Screenshots

|  Before  |  After  |
|--------|--------|
|||

## Testing in `sage-lib`

## Testing in `kajabi-products`

1. (**LOW/MEDIUM/HIGH/BREAKING**) Description of the change and its impact with QA as the audience.
   - [ ] One more examples of the component in use to either test the change or verify the change has not had adverse effects.

## Related

Closes [SAGE-316](https://kajabi.atlassian.net/browse/SAGE-316)

2022-05-04 14:16 UTC, ju-Skinner requested changes
Addition of or Updates to spec coverage.

2022-05-04 14:16 UTC, ju-Skinner commented on packages/sage-react/lib/themes/legacy/Banner/BannerContent.jsx
> +};
We need to add specs for this as well.

2022-05-05 14:52 UTC, anechol approved these changes
LGTM

2022-05-05 20:20 UTC, ju-Skinner approved these changes

2022-05-05 20:24 UTC, philschanely approved these changes
One quick tweak noted below but 👍 otherwise.

2022-05-05 20:55 UTC, merged