[Sage-500] Input Group - Fix Button Alignment
Kajabi/sage-lib pull request #1379
Opened 2022-05-03 15:04 UTC by anechol

## Description

Fixes button alignment within input.

## Screenshots

|  Before  |  After  |
|--------|--------|
<img width="560" alt="Screen Shot 2022-05-03 at 10 00 28 AM" src="https://user-images.githubusercontent.com/14791307/166479360-73c12b8d-b580-461a-9bd8-d186599e80c1.png">|<img width="570" alt="Screen Shot 2022-05-03 at 9 58 31 AM" src="https://user-images.githubusercontent.com/14791307/166479416-be49e6c2-9598-4f75-81e9-63d7fa021405.png">

## Testing in `sage-lib`

- View [Input Group](http://localhost:4000/pages/component/input_group)
- Check that button lines up with input

## Testing in `kajabi-products`

(LOW) Sage Next - Fixes button alignment within input.

## Related

[Sage-500](https://kajabi.atlassian.net/browse/SAGE-500)

2022-05-03 15:08 UTC, philschanely requested changes

2022-05-03 15:08 UTC, philschanely commented on packages/sage-assets/lib/stylesheets/themes/next/components/_button.scss
> +    padding: sage-spacing(xs) sage-spacing(sm);
Do you think this and the block also modified below could be combined if they're indeed for the same selector/context?

2022-05-03 15:08 UTC, philschanely commented on packages/sage-assets/lib/stylesheets/themes/next/components/_button.scss
> +    bottom: rem(1px);
Does this also work if the associated field has an error or hint/message activated?

2022-05-03 18:09 UTC, anechol commented on packages/sage-assets/lib/stylesheets/themes/next/components/_button.scss
> +    bottom: rem(1px);
Ah, thanks for reminding me!

2022-05-04 22:03 UTC, pixelflips approved these changes
LGTM!

2022-05-18 21:36 UTC, closed without merging

2022-05-18 21:43 UTC, anechol commented
Closing as this ticket has been completed.