[Sage-464] Tokens - Breakpoints Update
Kajabi/sage-lib pull request #1381
Opened 2022-05-04 21:58 UTC by anechol

## Description

Breakpoints before:
```
xs-max: 544px,
sm-min: 545px,
sm-max: 767px,
md-min: 768px,
md-max: 991px,
lg-min: 992px,
lg-max: 1199px,
xl-min: 1200px,
xxl-min: 1440px,
```

Updates breakpoints to the following values:
```
xxs-max: 699px,
xs-min: 700px,
xs-max: 799px,
sm-min: 800px,
sm-max: 989px,
md-min: 990px,
md-max: 1119px,
lg-min: 1120px,
lg-max: 1279px,
xl-max: 1280px,
xxl-min: 1440px,
```

## Testing in `sage-lib`

## Testing in `kajabi-products`

(LOW) Updates Sage Next breakpoints to new values.

## Related

[Sage-464](https://kajabi.atlassian.net/browse/SAGE-464)

2022-05-05 18:39 UTC, philschanely requested changes
Looking good. Did this include an audit of uses of the breakpoints to a) know what this impacts and b) potentially adjust any further?

2022-05-05 18:39 UTC, philschanely commented on packages/sage-assets/lib/stylesheets/themes/next/tokens/_breakpoints.scss
> +  xl-max: 1280px,
Here we should probably keep `min` but perhaps add a `xl-max` at 1439?

2022-05-06 21:56 UTC, anechol commented on packages/sage-assets/lib/stylesheets/themes/next/tokens/_breakpoints.scss
> +  xl-max: 1280px,
Thanks for pointing these out. i've made some updates. Let me know what you think.

2022-05-10 00:09 UTC, monkeypox8 approved these changes
👍🏼 LGTM. However, to @philschanely's point, this will have a far-reaching impact, particularly with the (soon to be deprecated) 12-col grid. A usage audit would be highly useful, perhaps as a related follow-up task.

2022-05-10 14:55 UTC, philschanely commented on packages/sage-assets/lib/stylesheets/themes/next/tokens/_breakpoints.scss
> +  xs-max: 767px,
This is ok. Since there are a few values in common between the old and new sets, would it make sense to only record the "new" breakpoints? And even then consider whether they are needed here for the whole system versus unique to specific needs in the new app frame? For example, if the new stop and 1120 is only for the change in sidebar size, it may suffice to scope it to that component or name it for that use case?

2022-05-11 15:51 UTC, anechol commented
After pairing with @philschanely and further evaluating the potential new breakpoints, the existing breakpoints we have for Sage will suffice for the new changes. Both the sidebar and 3-up layouts can be conformed to the existing 1199-1200px breakpoints. There will be no changes needed at this time so the PR will be closed.

2022-05-11 15:51 UTC, closed without merging