[Sage-552] Panel Controls, Toolbar - Alignment Fix
Kajabi/sage-lib pull request #1405
Opened 2022-05-12 20:52 UTC by anechol

## Description

Fixes alignment with components within the Panel Controls and Toolbar.

## Screenshots

|  Before  |  After  |
|--------|--------|
|||
<img width="1026" alt="Screen Shot 2022-05-12 at 3 49 08 PM" src="https://user-images.githubusercontent.com/14791307/168165605-d4cb0a6f-c8c5-41be-85c8-50cc414b7ec4.png">|<img width="1039" alt="Screen Shot 2022-05-12 at 3 38 41 PM" src="https://user-images.githubusercontent.com/14791307/168165626-0a20abab-3b8e-42dc-a509-fb201c0f05ab.png">
<img width="650" alt="Screen Shot 2022-05-12 at 3 49 00 PM" src="https://user-images.githubusercontent.com/14791307/168165654-ae671c16-808f-4636-94d2-c04df9b302a0.png">|<img width="654" alt="Screen Shot 2022-05-12 at 3 38 50 PM" src="https://user-images.githubusercontent.com/14791307/168165683-7eec7589-b794-48da-9316-76b3873d6bdb.png">

## Testing in `sage-lib`

- View [Panel Controls](http://localhost:4000/pages/component/panel_controls?tab=preview) and [Toolbar](http://localhost:4000/pages/component/toolbar?tab=preview)
- Check that alignment issues are resolved

## Testing in `kajabi-products`

(**LOW**) Fixes alignment with components within the Panel Controls and Toolbar.

## Related

[Sage-552](https://kajabi.atlassian.net/browse/SAGE-552)

2022-05-12 23:18 UTC, monkeypox8 requested changes
Looking great. I've added some comments around the scoping of the css custom props.

2022-05-12 23:18 UTC, monkeypox8 commented on packages/sage-assets/lib/stylesheets/themes/next/components/_toolbar.scss
> +  --icon-block-padding: #{rem(4px)};
Same here; consider moving under `.sage-toolbar` or `.sage-toolbar__group`

2022-05-13 19:24 UTC, pixelflips approved these changes
LGTM! Looks like things are aligning again, nice work! 👍🏼

2022-05-13 19:55 UTC, monicawheeler approved these changes

2022-05-13 21:11 UTC, QuintonJason approved these changes
Looking good

2022-05-13 21:41 UTC, merged