[SAGE-500] Input group button alignment
Kajabi/sage-lib pull request #1406
Opened 2022-05-13 20:45 UTC by QuintonJason

## Description

- [x] update the vertical alignment of the action buttons in the input group

## Screenshots

|  Before  |  After  |
|--------|--------|
|||

## Testing in `sage-lib`

## Testing in `kajabi-products`

1. (**LOW/MEDIUM/HIGH/BREAKING**) Description of the change and its impact with QA as the audience.
   - [ ] One more examples of the component in use to either test the change or verify the change has not had adverse effects.

## Related

2022-05-13 22:09 UTC, QuintonJason commented
![Screen Shot 2022-05-13 at 5 08 38 PM](https://user-images.githubusercontent.com/1241836/168395547-d25864e3-3264-4f6e-837d-5a72ff65d536.png)
 
This issue is a part of this Jira ticket, but the effort will be mainly done on the `kp` side cc @monkeypox8

2022-05-14 00:21 UTC, monkeypox8 requested changes
Looking great, left a comment about the `white-space` for the wrapped `affix` that I think we should address. The other comment I think we can address as a follow-up.

2022-05-14 00:21 UTC, monkeypox8 commented on packages/sage-assets/lib/stylesheets/themes/next/components/_form_input.scss
> +  }
Looks as though we'll need the `white-space: nowrap` on `.sage-input__affix` to correct this guy:

![seo-custom-url](https://user-images.githubusercontent.com/816579/168402966-5077901d-c765-49ad-bbc7-d1b9bc5285ba.png)

2022-05-14 00:21 UTC, monkeypox8 commented on packages/sage-assets/lib/stylesheets/themes/next/components/_button.scss
> +    position: absolute;
I'm wondering if we should raise the `z-index` to match the focus state of `sage-input__field`, if only as a temp patch until we can address an overhaul/deprecation of input group.

This one's not a blocker, because if the patch ends up interfering with prefix/suffix then it's probably better left as a follow-up. 

<details>
<summary>input focus state</summary>
<img src="https://user-images.githubusercontent.com/816579/168403137-c64c8dfc-b9dd-4b04-b786-36bd2e2b64c7.png" alt="">
</details>

2022-05-14 00:25 UTC, monkeypox8 commented
> This issue is a part of this Jira ticket, but the effort will be mainly done on the `kp` side cc @monkeypox8

@pixelflips when you have a chance on Monday, could you look into what sort of lift adjusting the payments panel controls would be to accommodate? From there we can see if Commerce has resources available to address.

2022-05-16 16:09 UTC, pixelflips commented
> @pixelflips when you have a chance on Monday, could you look into what sort of lift adjusting the payments panel controls would be to accommodate? From there we can see if Commerce has resources available to address.

@monkeypox8 Already have a stashed PR for payments just in case it came up. Wasn't sure if the sage updates would address it, but happy to help with that page if needed. Let me know what you think?

2022-05-18 17:54 UTC, monkeypox8 approved these changes
👍 LGTM, great work!

2022-05-18 18:35 UTC, merged