[Sage-718]- Remove legacy theme
Kajabi/sage-lib pull request #1515
Opened 2022-07-13 03:49 UTC by ju-Skinner

## Description
This is clearly a big PR. To help with reviewing, I'd suggest to either go commit by commit or pull it down locally and run. Should you prefer to do the latter, please make sure you stop all things Sage and start them back up. This will ensure that there are now cached objects and things compile as expected. 

## Screenshots
I'm electing not to include Screenshots, because I want to make sure we run locally. 

## Testing in `sage-lib`
Things to confirm:
* Docs site: http://localhost:4000
* Storybook: should now be on port 4100 again running the correct version of Sage (formerly Next)
* Style Dictionary Tokens:
  * React: packages/sage-react/lib/configs/dictionary/tokens.js
  * Rails: docs/lib/sage_rails/app/sage_tokens/

## Testing in `kajabi-products`
Separate PR will be issued for KP see [SAGE-719](https://kajabi.atlassian.net/browse/SAGE-719)

## Related

2022-07-13 15:23 UTC, QuintonJason approved these changes
Left one comment but this is good to go. `sage-lib` works and looks as expected

2022-07-13 15:39 UTC, anechol requested changes
Checked every Rails, React, and Sage Docs page I could find. Just one thing:

The [Grid Templates](http://localhost:4000/pages/patterns/grid_templates) page is broken due to a syntax error. Once that's done, we're good to go. Thanks for the huge effort!

2022-07-13 18:55 UTC, anechol approved these changes
Looking good!!

2022-07-13 18:57 UTC, monkeypox8 reviewed
This is looking great! Overall functionality is working as expected from what I'm seeing so far.

Question for the group: thoughts on keeping some aspect of the base "theme" structure in place? While `legacy`'s duplication should go, I could see a benefit in the ability to swap styles based off of CSS custom props/tokens, while keeping standard component markup/JS intact. But this being at the expense of complexity, I suppose a different approach to theming makes more sense.

There's also a few areas where the React/Storybook link is not functioning (Alert, Button, basically anywhere without a `Default` story view) but those are minor items that can be cleaned up later.

2022-07-13 18:59 UTC, ju-Skinner commented on docs/app/views/application/_assistant.html.erb
>        label_text: "Use Next theme",
Good catch, this should be removed. Thanks @QuintonJason

2022-07-13 19:01 UTC, ju-Skinner commented
> This is looking great! Overall functionality is working as expected from what I'm seeing so far.
> 
> Question for the group: thoughts on keeping some aspect of the base "theme" structure in place? While `legacy`'s duplication should go, I could see a benefit in the ability to swap styles based off of CSS custom props/tokens, while keeping standard component markup/JS intact. But this being at the expense of complexity, I suppose a different approach to theming makes more sense.
> 
> There's also a few areas where the React/Storybook link is not functioning (Alert, Button, basically anywhere without a `Default` story view) but those are minor items that can be cleaned up later.

I thought about that as well. Would be a good use case for "theming", light / dark.

2022-07-14 16:28 UTC, philschanely commented
@monkeypox8 no need for theming structure from my perspective. I believe if we find we need something along these lines we can devise a tactic for it specifically.

2022-07-14 16:49 UTC, monkeypox8 approved these changes
:shipit:

2022-07-14 17:32 UTC, pixelflips approved these changes
Clicked through docs and storybook and nothing jumped out. LGTM! 🔥 Great work!!

2022-07-14 17:45 UTC, ju-Skinner commented on docs/app/views/examples/layouts/frame/_main.html.erb
> +| `16p` | `lg` |
Thanks @goodwinchris

2022-07-14 18:11 UTC, goodwinchris approved these changes
🌝

2022-07-14 18:24 UTC, QuintonJason approved these changes
Clicked through and it works great!

2022-07-14 21:00 UTC, anechol approved these changes

2022-07-15 18:21 UTC, merged