fix(select components): add optgroup support to select component
Kajabi/sage-lib pull request #1533
Opened 2022-07-26 19:19 UTC by goodwinchris

## Description

## Screenshots

|  Before  |  After  |
|--------|--------|
|||

## Testing in `sage-lib`

## Testing in `kajabi-products`

1. (**LOW/MEDIUM/HIGH/BREAKING**) Description of the change and its impact with QA as the audience.
   - [ ] One more examples of the component in use to either test the change or verify the change has not had adverse effects.

## Related

2022-07-28 19:23 UTC, anechol approved these changes
LGTM

2022-07-29 00:32 UTC, monkeypox8 requested changes
Working great! The `key` in the `optgroup` loop, and possibly the if statement in the return are the only blockers from approval from what I can tell.

2022-07-29 00:32 UTC, monkeypox8 commented on packages/sage-react/lib/Select/Select.jsx
> +            <optgroup label={group.label} disabled={group.disabled}>
Similar to the `option` loop, these will also need a `key`.

2022-08-05 19:11 UTC, goodwinchris commented on packages/sage-react/lib/Select/Select.jsx
> +      // optionSelected = option.selected;
🔥

2022-08-05 19:11 UTC, goodwinchris commented on packages/sage-react/lib/Select/Select.jsx
> +      // optionSelected;
🔥

2022-08-05 19:12 UTC, goodwinchris commented on docs/lib/sage_rails/app/sage_components/sage_form_select.rb
> +    select_optgroups: [:optional, [[{
Look into clean up

2022-08-05 19:23 UTC, goodwinchris commented on docs/app/views/examples/components/form_select/_props.html.erb
> +  <td><%= md('An array of items that will serve as the `<select>`\'s `<option>`s and `<optgroup>`s.') %></td>
Question for reviewers: Should I add more detail here about _how_ to structure this?

2022-08-05 19:27 UTC, goodwinchris commented on docs/app/views/examples/components/form_select/_props.html.erb
> +  group_options: Array,
Question for reviewers: Should this have information about what can be contained in this array?

2022-08-05 23:06 UTC, monkeypox8 approved these changes
👍🏼 Added one suggestion on documentation

2022-08-11 13:25 UTC, QuintonJason approved these changes
Good to go. There's the non-blocking comment regarding the `Array` representation in the docs but still good.

2022-08-11 16:10 UTC, anechol approved these changes
LGTM

2022-08-11 19:45 UTC, ju-Skinner requested changes
See comments...Open to discuss and/or pair if you have questions.

2022-08-11 19:45 UTC, ju-Skinner commented on docs/lib/sage_rails/app/views/sage_components/_sage_form_select.html.erb
> +              </option>
This is a bit of tricky one. We are duplicating the same code down below, but this is also in a view in our library. Would be ideal to have a function helper to build out the options to reduce the code duplicity.

2022-08-11 19:45 UTC, ju-Skinner commented on packages/sage-react/lib/Select/Select.jsx
> +    const optgroupDisabled = optgroup.disabled;
do we need to set these values to a variable?

2022-08-11 19:45 UTC, ju-Skinner commented on packages/sage-react/lib/Select/Select.jsx
> +    if (typeof option === 'string') {
I would change this conditional check to something like 

```
if ( option.hasOwnProperty('label') ) {
  optionLabel = option.label;
  optionValue = option.value;
  optionDisabled = option.disabled;
}
else {
  optionLabel = option; 
  optionValue = option;
}

2022-08-11 19:46 UTC, ju-Skinner commented on docs/app/views/examples/components/form_select/_props.html.erb
> +  <td><%= md('An array of items that will serve as the `<select>`\'s `<option>`s and `<optgroup>`s.') %></td>
The more documentation you can provide for developers the better.

2022-08-12 18:28 UTC, ju-Skinner approved these changes
LGTM...great work

2022-08-12 19:01 UTC, philschanely approved these changes
Solid work here, @goodwinchris . 🏆

2022-08-12 20:09 UTC, merged