[SAGE-540] add Video Thumbnail component
Kajabi/sage-lib pull request #1534
Opened 2022-07-27 00:56 UTC by QuintonJason

## Description

- [x] add video thumbnail component (Rails)
- [x] add video thumbnail component (React)
- [x] add trigger to both
- [ ] ~add Video Thumbnail to hero~ -> [SAGE-726](https://kajabi.atlassian.net/browse/SAGE-726)

Design Spec: [KP Payouts -> Video Modal](https://www.figma.com/file/CEfffcNPgGDcDmknNt0HPj/COMM-1616-KP-Payouts?node-id=2822%3A22627)

## Screenshots

|  Before  |  After  |
|--------|--------|
|![videoThumbnailRails](https://user-images.githubusercontent.com/1241836/178278147-cb4cc57b-c494-4f4f-a143-0a8243cfe74a.gif)|![videoThumbnailReact](https://user-images.githubusercontent.com/1241836/178278173-d0b75ce4-252c-4403-9d86-1acd95c2225b.gif)|

## Testing in `sage-lib`

Visit the Video Thumbnail views and verify that it matches the design:
- [Rails](http://localhost:4000/pages/component/video_thumbnail?tab=preview#)
- [React](http://localhost:4110/?path=/story/sage-videothumbnail--default)

## Testing in `kajabi-products`

1. (**LOW**) Adds new Video Thumbnail component.

## Related

Closes [SAGE-540](https://kajabi.atlassian.net/browse/SAGE-540)

2022-07-27 18:18 UTC, QuintonJason commented
Bringing over this comment from original PR:
https://github.com/Kajabi/sage-lib/pull/1497#discussion_r919231891

2022-07-29 21:49 UTC, monkeypox8 requested changes
This is looking great. One minor cleanup item on the "Don'ts" bit and a question on the focus state to consider.

2022-07-29 21:49 UTC, monkeypox8 commented on docs/app/views/examples/components/video_thumbnail/_rules_dont.html.erb
> +<h3>Default Video Thumbnails</h3>
Was this left in by accident? Looks to be a duplicate of the preview markup

2022-07-29 21:49 UTC, monkeypox8 commented on docs/app/views/examples/components/video_thumbnail/_preview.html.erb
> +<%= sage_component SageModal, { id: "cool-modal" } do %>
:sunglasses:

2022-07-29 21:49 UTC, monkeypox8 commented on docs/lib/sage_rails/app/views/sage_components/_sage_video_thumbnail.html.erb
> +  style="background-image: url(<%= component.image_url %>);"
(non-blocking, future follow-up item) given that we won't be able to enforce appropriate image sizes and compression when in use, it'd seem beneficial for us to move away from background images. If we use `img` elements across the board, we can take advantage of the various built-in browser performance benefits.

2022-07-29 21:49 UTC, monkeypox8 commented on packages/sage-assets/lib/stylesheets/components/_video_thumbnail.scss
> +    width: rem(24px);
(non-blocking) Thoughts on setting these sizes (and those of the background) as variables for future theming adjustments? The play button does appear fairly large at mobile breakpoints vs the thumbnail, so I could see us wanting to tweak that later.

2022-07-29 21:49 UTC, monkeypox8 commented on packages/sage-assets/lib/stylesheets/components/_video_thumbnail.scss
> +    @include sage-focus-ring;
I'm unable to see a focus state on the thumbnail or button. Looks to be intentional, judging by line 55. If that's the case, I'd still recommend we display some sort of visual indication that the modal trigger is focused.

2022-08-11 14:44 UTC, QuintonJason commented on packages/sage-assets/lib/stylesheets/components/_video_thumbnail.scss
> +    @include sage-focus-ring;
Great callout, this has to do with the `overflow: hidden;` in the parent `sage-panel__figure`. I'll need to add a followup Jira ticket to address.

2022-09-06 18:12 UTC, QuintonJason commented
Closed as item is no longer needed. See ticket [SAGE-540](https://kajabi.atlassian.net/browse/SAGE-540)

2022-09-06 18:12 UTC, closed without merging