[Sage-761] Card - Add Interactivity
Kajabi/sage-lib pull request #1537
Opened 2022-07-28 20:33 UTC by anechol

## Description

Adds new prop for interactivity.

## Screenshots

|  Before  |  After  |
|--------|--------|
WIP|WIP

## Testing in `sage-lib`

WIP

## Testing in `kajabi-products`

WIP

## Related

[Sage-761](https://kajabi.atlassian.net/browse/SAGE-761)

2022-08-15 15:52 UTC, QuintonJason commented on packages/sage-assets/lib/stylesheets/components/_card.scss
> +  a:not(.sage-link--primary),
Can the class be something tied to the card, like `.sage-card__link--primary`? Currently `sage-link--primary` can be used outside of the card and would reduce any edge cases.

2022-08-15 15:53 UTC, QuintonJason commented on packages/sage-assets/lib/stylesheets/components/_link.scss
> +    &:focus::after {
This may also need to be a `box-shadow` as this is currently showing two borders.

2022-08-15 15:58 UTC, QuintonJason requested changes
![Screen_Shot_2022-08-15_at_10_49_38_AM](https://user-images.githubusercontent.com/1241836/184669968-ba5e925e-c9cd-4fae-bea2-91b2f4856cdc.png)
1. Design may need to provide feedback, but the primary target in an interactive card looks similar to the primary target for a Catalog Item or a Table Row. The treatment seems weight related.
2. When the Card is `:active` and `:focus`ed two rings are showing. Does an active card need a focus state as well? This may be something design has to weigh in on

2022-08-15 20:10 UTC, anechol commented on packages/sage-assets/lib/stylesheets/components/_link.scss
> +    &:focus::after {
Addressed this. Removed the shadow on the `after` and placed it on the `before`.

2022-08-15 20:11 UTC, anechol commented
Updated to make the Sage Card primary action resemble primary links in tables and lists.

2022-08-16 18:33 UTC, goodwinchris commented
I see your most recent comment about updating link styles. Just want to confirm (I'm still learning here) the expected visual is how its shown in my attached screenshot and not what's shown in the PR description?
<img width="1003" alt="CleanShot 2022-08-16 at 14 32 51@2x" src="https://user-images.githubusercontent.com/791670/184953162-b6a03959-d6b4-4f7d-a2a8-635622be7ecf.png">

2022-08-18 18:44 UTC, anechol commented
> I see your most recent comment about updating link styles. Just want to confirm (I'm still learning here) the expected visual is how its shown in my attached screenshot and not what's shown in the PR description? <img alt="CleanShot 2022-08-16 at 14 32 51@2x" width="1003" src="https://user-images.githubusercontent.com/791670/184953162-b6a03959-d6b4-4f7d-a2a8-635622be7ecf.png">

Thanks for calling that out @goodwinchris, I've replaced the video in the description.

2022-08-18 19:45 UTC, ju-Skinner approved these changes
LGTM

2022-08-18 19:46 UTC, QuintonJason approved these changes

2022-08-18 19:48 UTC, merged