Pagination: (React) Adjust default value of `pageCount` for improved use
Kajabi/sage-lib pull request #1561
Opened 2022-08-17 18:50 UTC by philschanely

## Description

Per SAGE-751 description, React Pagination defaults `pageCount` to `1` which makes page calculation moot. By setting it to default of `null` it becomes dependent on the user to provide `pageCount` for a specific number of pages or to provide `itemsTotalCount` and `pageSize` for the page count to be calculated better.

## Screenshots

No visual changes.

## Testing in `sage-lib`

See the following for improved stories showing the two configuration options.

- http://localhost:4100/?path=/story/sage-pagination--from-page-count 
- http://localhost:4100/?path=/story/sage-pagination--from-calculated-pages

## Testing in `kajabi-products`

1. (**LOW**) Adjust default value for `pageCount` in React Pagination for easier configuration. Also audited existing uses of Pagination to ensure no breaking changes or impact on uses. 👍 

## Related

https://kajabi.atlassian.net/browse/SAGE-751

2022-08-18 14:07 UTC, QuintonJason requested changes
Please consider rebasing as this contains other PR work

2022-08-22 15:59 UTC, pixelflips approved these changes

2022-08-25 15:19 UTC, ju-Skinner commented on packages/sage-react/lib/Pagination/Pagination.jsx
> +  pageCount: null,
Based on our conversation via huddle...It looks like we can clean up the logic that uses the property. With programming there are two ways to  clean this up, neither are wrong.

**first**
```
  let localPageCount = canCalculatePageRange 
    ? Math.ceil(itemsTotalCount / pageSize) 
    : 1;
  if (pageCount) {
    localPageCount = pageCount;
  }
  ```
**second**
```
  switch (true) {
    case pageCount:
      localPageCount = pageCount;
      break;
    case canCalculatePageRange:
      localPageCount = Math.ceil(itemsTotalCount / pageSize);
      break;
    default:
      localPageCount = 1;
      break;
  }
  ```

2022-08-25 15:46 UTC, ju-Skinner commented on packages/sage-react/lib/Pagination/Pagination.jsx
> +      break;
**Note**:  Since the primary expression `switch(true)` is always true, the case statements themselves need to be an expression or act as an `if` statement in other words. 

excerpt taken from [switch](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch)
>switch (true) pattern as an alternative to if...else

2022-08-25 15:46 UTC, ju-Skinner approved these changes

2022-08-26 13:57 UTC, merged