PageHeading: Adjust React proptypes
Kajabi/sage-lib pull request #1562
Opened 2022-08-18 12:47 UTC by philschanely

## Description

This PR adjusts the proptypes for actionItems and toolbarItems to be just nodes rather than an array of nodes in keeping with a more conventional approach to such props in React.

## Screenshots

No visual impact.

## Testing in `sage-lib`

See http://localhost:4100/?path=/story/sage-pageheading--default and other related stories to see no visual change in output.

## Testing in `kajabi-products`

1. (**LOW**) Adjust proptype setting for toolbarItems and actionItems to expect just a node rather than an array of nodes. 

## Related

[SAGE-752](https://kajabi.atlassian.net/browse/SAGE-752)

2022-08-18 14:56 UTC, ju-Skinner requested changes
See comments.

2022-08-18 14:56 UTC, ju-Skinner commented on packages/sage-react/lib/PageHeading/PageHeading.jsx
> +  actionItems: PropTypes.node,
Could you provide more context around the reasoning for the change here? Both prop names `actionItems` and `toolbarItems` are named in a way (plural naming) that indicate they are to contain multiple items. This seems to indicate better use for an array over node usage.

Also, looking at the ticket you referenced  [SAGE-752](https://kajabi.atlassian.net/browse/SAGE-752), there is no context as to the "why" for this change. To help me, and possibly others, better review this, could you add more context and details to the change? This can be done either here via PR review or an ad-hoc zoom meeting.

2022-08-18 14:56 UTC, ju-Skinner commented on packages/sage-react/lib/PageHeading/PageHeading.story.jsx
> +  ),
Same comment applies here as well, but in regards to `toolbarItems`.

2022-08-18 14:56 UTC, ju-Skinner commented on packages/sage-react/lib/PageHeading/PageHeading.story.jsx
> +  },
To piggyback off of my above comments, you can see here in the story, that we are still listing multiple "action items"; in this case `buttons`.

2022-08-18 16:09 UTC, philschanely commented on packages/sage-react/lib/PageHeading/PageHeading.jsx
> +  actionItems: PropTypes.node,
Great points, @ju-Skinner ! 🙌 and thanks for the quick zoom sync too. I have updated the PR description to call out more clearly:

- we have an opportunity to align better with how these similar aspects are named in Rails, and
- we have an opportunity to align better with convention we have in React for how slots like this are typed and rendered.

Also given these changes I'm updating the classification of this change to be a breaking change. The PR on the `kp` side is also updated to match.

2022-08-19 13:33 UTC, ju-Skinner commented on packages/sage-react/lib/PageHeading/PageHeading.jsx
> +  toolbar,
Seeing this property makes me believe that we are to pass a Toolbar component. I know you we somewhat opposed to using `toolbarContent` but I believe the more clear we can be with the use or placement the easier it is for devs.

2022-08-19 13:37 UTC, ju-Skinner requested changes
See most recent comment regarding `toolbar` param

2022-08-19 18:01 UTC, philschanely commented on packages/sage-react/lib/PageHeading/PageHeading.jsx
> +  toolbar,
@ju-Skinner Thanks! I think there are multiple correct/good ways to look at it, so I'd like to see what some other colleagues think. Do you feel the same way about `actions` which is also a content slot here?

Def open to going with a team consensus so looking forward to see what others think 🙌

2022-08-19 18:34 UTC, pixelflips commented on packages/sage-react/lib/PageHeading/PageHeading.jsx
> +  toolbar,
I can understand both points here, but it almost seems like to-may-to vs to-mah-to. IMHO, it seems like we need to decide if our priority at the moment is semantics or consistency.

While both are viable options for sure, I'd lean toward consistency right now, and if we want to think more about semantics (eg. prop naming) that could be addressed in a larger follow-up. I feel like we'd want to keep those aligned in both areas even if we do decide to change the naming. 

Overall not sure if that helps or not, but just thoughts since it was requested.

2022-08-22 15:59 UTC, pixelflips approved these changes

2022-08-25 14:24 UTC, philschanely commented on packages/sage-react/lib/PageHeading/PageHeading.jsx
> +  toolbar,
@ju-Skinner it sounds like we're open overall here but consensus leans to `toolbar` for now. Is this important enough to you that we should change to `toolbarContent` now?

2022-08-25 14:48 UTC, ju-Skinner approved these changes
Approved, but see comment.

2022-08-25 14:48 UTC, ju-Skinner commented on packages/sage-react/lib/PageHeading/PageHeading.jsx
> +  toolbar,
@philschanely Overall, I still think the naming of these should be changed, but for the sake of consistency between rails and react, we can go with `toolbar` and `actions`. 

I agree with both @monkeypox8 and @pixelflips with having a larger initiative for these to follow a standard,  which then they would be documented.

2022-08-25 15:21 UTC, merged