[SAGE-324] align rails and react spinner
Kajabi/sage-lib pull request #1588
Opened 2022-09-14 21:50 UTC by QuintonJason

## Description

- [x] align the rails and react loading spinner
    
- [x] create Toast stories
    - [x] Self Dismissing Toasts
    - [x] Danger Toasts
    - [x] Loading Toasts
    - [x] Toast with Link

## Screenshots

#### Loading spinner
|  Rails  |  React  |
|--------|--------|
|![loading-rails](https://user-images.githubusercontent.com/1241836/190268416-3c09bffa-8685-4f9e-ac7c-70321acc4bf2.gif)|![loading-react](https://user-images.githubusercontent.com/1241836/190268432-9debe846-54b4-4843-86b5-8aeaa9d945ed.gif)|

## Testing in `sage-lib`

Visit the Toast views and verify that the loading spinner looks the same in Rails and React:
- [Rails](http://localhost:4000/pages/component/toast?tab=preview)
- [React](http://localhost:4100/?path=/story/sage-toast--loading-toasts)

## Testing in `kajabi-products`

1. (**MEDIUM**) Updates for styles of the spinner in the React component.

## Related

Closes [SAGE-324](https://kajabi.atlassian.net/browse/SAGE-324)

2022-09-14 21:51 UTC, QuintonJason commented
@ju-Skinner looking for guidance on these tests

2022-09-19 15:59 UTC, pixelflips requested changes
Functionally, everything seems to be working as expected. One area where I noticed a UI difference is when multiple toasts are fired. The toast messages don't stack one above the other on the react side. Instead, they overlay each other.

|  Rails (multiple)  |  React (multiple)  |
|--------|--------|
|<img width="397" alt="Screen Shot 2022-09-19 at 8 52 53 AM" src="https://user-images.githubusercontent.com/1175111/191060817-8fb5eddd-b92d-4d65-85be-f6ca3aa9dde6.png">|<img width="492" alt="Screen Shot 2022-09-19 at 8 53 17 AM" src="https://user-images.githubusercontent.com/1175111/191060895-49562c98-a362-4d97-b782-ad86d12b704a.png">|

2022-09-19 20:30 UTC, QuintonJason commented
> Functionally, everything seems to be working as expected. One area where I noticed a UI difference is when multiple toasts are fired. The toast messages don't stack one above the other on the react side. Instead, they overlay each other.
> 
> Rails (multiple)	React (multiple)
> <img alt="Screen Shot 2022-09-19 at 8 52 53 AM" width="397" src="https://user-images.githubusercontent.com/1175111/191060817-8fb5eddd-b92d-4d65-85be-f6ca3aa9dde6.png">	<img alt="Screen Shot 2022-09-19 at 8 53 17 AM" width="492" src="https://user-images.githubusercontent.com/1175111/191060895-49562c98-a362-4d97-b782-ad86d12b704a.png">

@pixelflips which view does you use to recreate this situation?

2022-09-19 20:35 UTC, pixelflips commented
> @pixelflips which view does you use to recreate this situation?

@QuintonJason In rails, I just clicked multiple buttons. In react, I switched to the docs tab and then clicked multiple buttons. Let me know if that helps to clarify. Happy to pair up if needed.

2022-09-19 21:36 UTC, pixelflips approved these changes
After pairing up and taking a closer look at the issues I mentioned, those seem to be specifically storybook-related and non-issues.

LGTM! 👍🏼  Nice work!

2022-09-22 00:20 UTC, monkeypox8 approved these changes
👍 LGTM, no concerns here

2022-09-22 13:45 UTC, goodwinchris requested changes

2022-12-05 16:48 UTC, QuintonJason commented
Closing this PR as this functionality is already existing in the `Toast` component by setting `timeout={false}`

2022-12-05 16:48 UTC, closed without merging