Simplify Rails Alert docs
Kajabi/sage-lib pull request #1600
Opened 2022-09-27 14:50 UTC by philschanely

## Description

This PR simplifies the Alert docs pages as follows:

- [x] Reduces redundancy; not all colors need to be shown for every example set.
- [x] Adds/revises sections:
   - [x] Dismissible alerts
   - [x] Alert actions
   - [x] Small alerts

## Screenshots

| Before | After |
|---|---|
| ![Screen Shot 2022-09-27 at 10 47 23 AM](https://user-images.githubusercontent.com/17955295/192559548-87ccb6fb-0ec9-42fc-9263-12c45af4e19c.png) ![Screen Shot 2022-09-27 at 10 47 42 AM](https://user-images.githubusercontent.com/17955295/192559602-c8b1f9e5-0539-4652-8543-bcb576f1be0f.png) ![Screen Shot 2022-09-27 at 10 47 58 AM](https://user-images.githubusercontent.com/17955295/192559692-4030ed6f-295b-4097-8e8c-e3dd4d2fa5c1.png) ![Screen Shot 2022-09-27 at 10 48 06 AM](https://user-images.githubusercontent.com/17955295/192559759-83d62624-9d52-4000-b36b-88cb16ab714b.png) | ![Screen Shot 2022-09-27 at 10 42 03 AM](https://user-images.githubusercontent.com/17955295/192557999-7cdd152e-9857-4196-973a-7d00dc28e958.png) ![Screen Shot 2022-09-27 at 10 42 19 AM](https://user-images.githubusercontent.com/17955295/192558031-77bc2026-042c-4438-b395-120c4d21a2e6.png) ![Screen Shot 2022-09-27 at 10 42 29 AM](https://user-images.githubusercontent.com/17955295/192558064-5e6074ca-5693-49d4-bcbf-1bee9598cdd0.png) |

## Testing in `sage-lib`

See http://localhost:4000/pages/component/alert?tab=preview

## Testing in `kajabi-products`

1. (**LOW**) Documentation updates to Alert page

## Related

https://kajabi.atlassian.net/browse/DSS-168

2022-10-11 15:50 UTC, pixelflips requested changes
Great updates here and much cleaner overall. I am seeing some oddities in that icons are not showing and actions are centered. I refreshed a few times so let me know if I am missing something.

<img width="930" alt="Screen Shot 2022-10-11 at 8 48 07 AM" src="https://user-images.githubusercontent.com/1175111/195139749-fc57248d-f0d5-4d84-a001-45be038b3fd5.png">

2022-10-12 14:10 UTC, philschanely commented
Woops! Sorry about that @pixelflips . Fixed now.

2022-10-12 15:52 UTC, pixelflips approved these changes
LGTM! Great work and a nice improvement!! 👍🏼

2022-10-12 15:54 UTC, ju-Skinner approved these changes
💯

2022-10-12 16:34 UTC, merged