[DSS-156] Tag - Image Variant
Kajabi/sage-lib pull request #1602
Opened 2022-09-28 19:53 UTC by anechol

## Description

Adds image variation for the Tag component.

## Screenshots

<img width="467" alt="Screen Shot 2022-09-28 at 2 37 49 PM" src="https://user-images.githubusercontent.com/14791307/192875293-bd3e5ee2-ed8e-49ae-b4cb-34d26e966185.png">

## Testing in `sage-lib`

### Rails
- View [Tag](http://localhost:4000/pages/component/tag?tab=preview)
- Check that component matches Figma specs

### React
- View [Tag](http://localhost:4100/?path=/docs/sage-tag--default)
- Check that component matches Figma specs

## Testing in `kajabi-products`

(**LOW**) Adds image variation for the Tag component.

## Related

[DSS-156](https://kajabi.atlassian.net/browse/DSS-156)

2022-09-28 20:29 UTC, pixelflips requested changes

2022-09-29 13:22 UTC, philschanely reviewed
A few suggestions here, but looking good!

2022-09-29 13:22 UTC, philschanely commented on packages/sage-react/lib/Tag/Tag.jsx
>        className={classNames}
Is the new root tag modifier missing in `classnames(...)` above as well?

2022-09-29 15:22 UTC, anechol commented
Thanks @philschanely @pixelflips, I've addressed all the comments and stuff I've missed.

2022-09-29 15:36 UTC, pixelflips approved these changes
One minor comment around documentation, but otherwise LGTM! Nice work! 👍🏼

2022-09-29 15:36 UTC, pixelflips commented on docs/app/views/examples/components/tag/_preview.html.erb
> +		image: "avatar/koray_okumus.png",
Should we update the properties tab to document the new image?

2022-09-29 18:39 UTC, anechol commented on docs/app/views/examples/components/tag/_preview.html.erb
> +		image: "avatar/koray_okumus.png",
Done!

2022-09-30 14:46 UTC, philschanely approved these changes
Looks great! 🙌

2022-09-30 16:17 UTC, cameronsimony approved these changes
👍

2022-09-30 18:15 UTC, merged