[DSS-157] Avatar - Custom Icon and Color
Kajabi/sage-lib pull request #1605
Opened 2022-09-29 14:44 UTC by anechol

## Description

Adds props to allow for custom colors and icons.

## Screenshots

|  Before  |  After  |
|--------|--------|
WIP|WIP

## Testing in `sage-lib`

WIP

## Testing in `kajabi-products`

(**LOW**) Adds props to allow for custom colors and icons.

## Related

[DSS-157](https://kajabi.atlassian.net/browse/DSS-157)

2022-10-06 15:29 UTC, ju-Skinner approved these changes

2022-10-06 15:34 UTC, philschanely approved these changes
Looks great!

Not blocking, but what do you think about restructuring so that rather than `badge`, `badgeColor`, and `badgeIcon` we just have `badge` but it can accept just `true` (for default badge) or a hash/object with optional `icon` and `color` properties for encapsulating the custom settings?

2022-10-06 15:38 UTC, pixelflips reviewed
I can't quite work out if it's a Storybook issue, but when I set badge to true and adjust the badge color and icon, it changes the icon color and not the background color.

Happy to pair if it's not obvious.

<img width="1035" alt="Screen Shot 2022-10-06 at 8 34 37 AM" src="https://user-images.githubusercontent.com/1175111/194357106-54b17032-0f67-484b-82f6-25eb350f9ac3.png">

2022-10-06 18:06 UTC, monkeypox8 approved these changes
👍 LGTM, with one note for the badge appearance:

Requirements for the issue are unclear on this, but the Figma mocks are displaying various social media logo badges with varying background color fills.

The issue that @pixelflips is seeing is because the icon examples in Rails are using `-filled` variants. If the intent will be to allow the `badge_color` to affect the background, then we'll have to ask Design to add those versions of the icons as well. Otherwise, it's working as intended.

2022-10-06 18:27 UTC, anechol commented
@pixelflips @monkeypox8 Thanks for the feedback here. I just spoke to Quinton about this issue and yes, it looks like this is going to have to be brought up to design. Filled icons are working as intended, but those with only strokes are going to look awkward. Going to bring this up in the team sync for ideas.

2022-10-07 19:05 UTC, anechol commented
Per feedback from the team and design, I'll be implementing a solution for both a foreground (icon stroke/fill) and background color.

2022-10-12 16:07 UTC, pixelflips requested changes
Code looks great, but I am seeing an issue with Storybook. When setting Badge to `true` and then trying to add a `string` for the `badgeBackgroundColor` the screen goes blank and an error shows in the console.


https://user-images.githubusercontent.com/1175111/195393080-a29cb9ad-f369-45d6-b648-eaf9069b505e.mov

2022-10-12 16:37 UTC, anechol commented
> Code looks great, but I am seeing an issue with Storybook. When setting Badge to `true` and then trying to add a `string` for the `badgeBackgroundColor` the screen goes blank and an error shows in the console.
> 
>  Screen.Recording.2022-10-12.at.9.02.01.AM.mov

Yeah @pixelflips this is a weird issue, and I think it's Storybook related, but can't confirm entirely. If you set the background color first and then set badge to true, then it works as inspected.

2022-10-12 17:19 UTC, pixelflips commented
> Yeah @pixelflips this is a weird issue, and I think it's Storybook related, but can't confirm entirely. If you set the background color first and then set badge to true, then it works as inspected.

@anechol it is weird for sure, maybe @ju-Skinner or @philschanely have thoughts on the error I mentioned above. 🤞🏼

2022-10-12 21:33 UTC, anechol commented
@monkeypox8 Thanks for the pointer. I adjusted the conditional so this should work fine in storybook now.

2022-10-12 21:35 UTC, anechol commented
> While continuing to review and changing up the controls, also noticed that the icons seem to break out in some cases. Will drop a screenshot so you can see the controls.
> 
> ![Screen Shot 2022-10-12 at 10 16 19 AM](https://user-images.githubusercontent.com/1175111/195407186-24a54e39-ee88-4293-ad4a-fae5e2449f2c.png)

Ahh thanks for pointing this out @pixelflips . I might have to look into this further as I'm not sure what's a good solution to handle every use case for every icon in the library 🤔

2022-10-12 22:31 UTC, monkeypox8 approved these changes
👍 LGTM! Left a note on one cleanup item to consider.

2022-10-12 22:31 UTC, monkeypox8 commented on packages/sage-react/lib/Avatar/Avatar.jsx
> +          style={({
(non-blocking) You can also drop the enclosing parentheses `()` here now that the conditional has been removed.

2022-10-12 22:35 UTC, monkeypox8 commented
> I might have to look into this further as I'm not sure what's a good solution to handle every use case for every icon in the library 🤔

Agreed; this is going to be pretty difficult to solve without a change to our icon system sizing, so I'm inclined to leave it for another day if the group's on board. Right now the use case for custom badges is limited. But if it does become an issue, we could always apply a 90% scale transform or something similar, though it'd have to be across the board.

2022-10-13 14:49 UTC, ju-Skinner approved these changes
great job. Thanks for adding specs.

2022-10-14 16:24 UTC, cameronsimony approved these changes
👍 👍

2022-10-14 16:25 UTC, merged