Checkbox: Ensure storybook shows props and code
Kajabi/sage-lib pull request #1618
Opened 2022-10-05 16:23 UTC by philschanely

## Description

This PR adds props onto Checkbox to ensure the Storybook documentation is more useful to engineers.

## Screenshots

| | Before | After |
|---|---|---|
| Props table | ![Screen Shot 2022-10-05 at 12 09 46 PM](https://user-images.githubusercontent.com/17955295/194111261-907ad23e-d661-4ba9-9e12-e10cabf4e78c.png) | ![Screen Shot 2022-10-05 at 12 22 03 PM](https://user-images.githubusercontent.com/17955295/194111402-ed8477eb-bb3a-48ac-8be0-8d13a6fa8d14.png) |
| Show code | ![Screen Shot 2022-10-05 at 12 09 38 PM](https://user-images.githubusercontent.com/17955295/194111241-2aed9530-c691-47b4-83c3-496117bd650c.png) | ![Screen Shot 2022-10-05 at 12 21 47 PM](https://user-images.githubusercontent.com/17955295/194111365-14cca54e-b6a2-421b-89ee-05f1cf2bf32b.png) |

## Testing in `sage-lib`

- See http://localhost:4100/?path=/docs/sage-checkbox--default

## Testing in `kajabi-products`

1. (**LOW**) Improve documentation for React Checkbox component

## Related

https://kajabi.atlassian.net/browse/DSS-192

2022-10-05 16:39 UTC, pixelflips requested changes
I am seeing checked and the partial selection examples are appearing incorrectly.

![Screen Shot 2022-10-05 at 9 38 46 AM](https://user-images.githubusercontent.com/1175111/194114912-f6d0eb14-354c-45dc-aa1b-529e0877cba5.png)

2022-10-05 18:09 UTC, philschanely commented
Great catch, @pixelflips! ☺️

2022-10-05 18:10 UTC, pixelflips approved these changes
LGTM! 👍🏼

2022-10-07 14:42 UTC, QuintonJason approved these changes

2022-10-11 14:34 UTC, merged