[]Dss 155
Kajabi/sage-lib pull request #1620
Opened 2022-10-07 01:40 UTC by QuintonJason

## Description

## Screenshots

|  Before  |  After  |
|--------|--------|
|||

## Testing in `sage-lib`

## Testing in `kajabi-products`

1. (**LOW/MEDIUM/HIGH/BREAKING**) Description of the change and its impact with QA as the audience.
   - [ ] One more examples of the component in use to either test the change or verify the change has not had adverse effects.

## Related

2022-10-13 17:34 UTC, pixelflips requested changes
Briefly started looking at this one. The accordion looks great but seeing some styling issues and `accordion-panel.js` related errors on the Expandable card page.

<img width="2555" alt="Screen Shot 2022-10-13 at 10 33 06 AM" src="https://user-images.githubusercontent.com/1175111/195666315-52297069-e1fa-4391-abb0-de0510628a40.png">

2022-10-14 00:11 UTC, monkeypox8 requested changes
Looks like the overlap with Expandable Card is causing some issues with this one.

2022-10-14 00:11 UTC, monkeypox8 commented on packages/sage-assets/lib/stylesheets/components/_expandable_card.scss
> +    transform: rotateZ(90deg);
Icon position in react is inheriting `sage-expandable-card` styles:

<details>
<summary>icon position</summary>
<img src="https://user-images.githubusercontent.com/816579/195733520-fc399d1e-432c-49f5-9fb5-25f75d072415.png" alt="">
</details>

2022-10-14 15:59 UTC, pixelflips approved these changes
LGTM! I noted a few minor styling issues, but I am no longer seeing errors, and the accordion is working great. Nice work! 👍🏼

2022-10-14 15:59 UTC, pixelflips commented on packages/sage-assets/lib/stylesheets/components/_expandable_card.scss
> -    margin-top: sage-spacing(xs);
Is this deletion intentional? It's causing the spacing between the trigger and the body to be reduced.

2022-10-14 15:59 UTC, pixelflips commented on packages/sage-assets/lib/stylesheets/components/_button.scss
> +  .sage-accordion &.sage-expandable-card__trigger {
On `:hover` the background color is clipping the border. 

![Screen Shot 2022-10-14 at 8 50 24 AM](https://user-images.githubusercontent.com/1175111/195889769-fe6f02a7-2499-458b-84e5-deed0b12f7af.png)

2022-10-14 16:09 UTC, anechol requested changes
This is looking very good so far! Just a question here:

On Rails under the example "one open at a time", should the Accordion that's already open be closed when clicking it again? Currently it's not doing that.

2022-10-17 17:31 UTC, anechol approved these changes
LGTM! Nice work on this.

2022-10-17 19:53 UTC, monkeypox8 reviewed
Looking good; one change to the `accordion-panel.js` should get expandable card working again in Rails.

2022-10-17 19:53 UTC, monkeypox8 commented on packages/sage-system/lib/accordion-panel.js
> +    if (accordion != null) {
Because this conditional is scoping all the functionality to `accordion`, it prevents expandable card from toggling. Moving lines 47-51 out should get that sorted.

2022-10-19 02:25 UTC, monkeypox8 approved these changes
👍 LGTM, nice work!

2022-10-19 02:25 UTC, monkeypox8 commented on packages/sage-system/lib/accordion-panel.js
> +    if (accordion != null) {
(non-blocking) mostly personal preference, but we can combine the two conditionals here now that the other block has been removed:
```if (accordion !== null && accordion.classList.contains(CLASS_ACCORDION_ONE_PANEL_EXPANDED)) {```

2022-10-27 23:00 UTC, merged