[DSS-187] add Priority Plus navigation pattern
Kajabi/sage-lib pull request #1626
Opened 2022-10-21 16:46 UTC by QuintonJason

## Description

## Screenshots

|  Before  |  After  |
|--------|--------|
|||

## Testing in `sage-lib`

## Testing in `kajabi-products`

1. (**LOW/MEDIUM/HIGH/BREAKING**) Description of the change and its impact with QA as the audience.
   - [ ] One more examples of the component in use to either test the change or verify the change has not had adverse effects.

## Related

2022-11-09 14:13 UTC, ju-Skinner commented on packages/sage-react/lib/Toolbar/Toolbar.story.jsx
> +  maximumNumberInNav: 8
These properties are no longer needed.

2022-11-09 14:14 UTC, ju-Skinner commented on packages/sage-react/lib/Toolbar/ToolbarEditor.jsx
> +import debounce from 'lodash/debounce';
we need to fix this error by running `yarn lerna add lodash --scope=@kajabi/sage-react --dev`

2022-11-09 14:41 UTC, ju-Skinner requested changes
Changes are requested due to the unused args listed in the Story (see previous comments above).

Also, we need to show how to use this in a production like environment. What I mean by this, the stories currently show two different approaches.  This may be a time we we can leverage a MDX story to use our words to explain more on how to implement and use.

2022-11-09 14:41 UTC, ju-Skinner commented on packages/sage-react/lib/Toolbar/ToolbarEditor.story.jsx
> +const PoCTemplate = () => (
Do we need both stories?

2022-11-09 19:15 UTC, pixelflips approved these changes
A couple of minor comments, but nothing blocking. Besides the lodash error and Julian's comments, LGTM! Great work! 👍🏼

2022-11-09 19:15 UTC, pixelflips commented on packages/sage-assets/lib/stylesheets/components/_toolbar_editor.scss
> +    border-left: 1px solid sage-color(grey, 400);
could `sage-border()` be used here?

2022-11-09 19:15 UTC, pixelflips commented on packages/sage-react/lib/Toolbar/ToolbarEditor.jsx
> +    // console.log('More Items: ', fullNavArray.slice(sliceIdx));
Are these still needed or could they be removed?

2022-11-09 19:15 UTC, pixelflips commented on packages/sage-react/lib/Toolbar/ToolbarEditor.jsx
> +  // console.log('Name: ', name, 'Priority Items: ', priorityItems, ' More Items: ', moreItems);
Could this be removed?

2022-11-09 19:15 UTC, pixelflips commented on packages/sage-react/lib/Toolbar/ToolbarEditor.story.jsx
> +        component: 'Toolbar Editor is used for places like toolbar'
Could the description be updated to help clarify and reduce any confusion with the `<Toolbar>` component?

2022-11-10 19:46 UTC, monkeypox8 reviewed
Looking great so far; appears to work well enough in isolation. Noted a few items to consider.

2022-11-10 19:46 UTC, monkeypox8 commented on packages/sage-react/lib/Toolbar/ToolbarEditor.story.jsx
> +      <Button
Longstanding issue but relevant here: `iconOnly` buttons are not displaying readable labels. As it currently stands, the buttons output the icon unicode to assistive devices, so not exactly helpful.

It's difficult to solve for because the issue is universal, not limited to just this use case. Short of a refactor of the button component I'm not certain we have an intermediate fix.

2022-11-15 22:38 UTC, pixelflips approved these changes
A couple of non-blocking comments. Overall this is really nice and the documentation is great! LGTM! 👍🏼

2022-11-15 22:38 UTC, pixelflips commented on packages/sage-react/lib/Button/Button.jsx
> +  selected: PropTypes.bool,
just a note and not a blocker, but `selected` feels slightly odd to me. wondering if something like `active` may be less odd. Def not a show-stopper and am happy to go with the group consensus.

2022-11-15 22:38 UTC, pixelflips commented on packages/sage-assets/lib/stylesheets/components/_button.scss
> +    margin-right: rem(3px);
`margin-inline` maybe?

2022-11-16 01:48 UTC, QuintonJason commented on packages/sage-react/lib/Button/Button.jsx
> +  selected: PropTypes.bool,
i'm definitely down to change it to `active` but didn't want to confuse with `:active`. Interested to hear others' thoughts on this.

2022-11-16 15:09 UTC, ju-Skinner commented on packages/sage-react/lib/Button/Button.jsx
> +  selected: PropTypes.bool,
Is this supposed to be a way to identify if the button is in the `pressed` state?

2022-11-16 15:12 UTC, QuintonJason commented on packages/sage-react/lib/Button/Button.jsx
> +  selected: PropTypes.bool,
No, if that button was used for the selected text.

2022-11-16 15:13 UTC, ju-Skinner commented on packages/sage-react/lib/Dropdown/RichEditorDropdown.jsx
> -    label="Add an element"
Is this component only being used for the `ToolbarEditor` component? If so, no concern here. Otherwise do we want this change, and if so how will it affect other places it's currently being used.

2022-11-16 16:16 UTC, ju-Skinner approved these changes

2022-11-17 19:05 UTC, merged