[SAGE-214]: Add horizontal alignment logic to grid rows
Kajabi/sage-lib pull request #1632
Opened 2022-11-04 20:57 UTC by goodwinchris

## Description
Adding the ability to set horizontal alignment in our grid rows using `horizontalAlignment`.

## Screenshots
Rails | React
--|--
<img width="1302" alt="CleanShot 2022-11-04 at 16 50 28@2x" src="https://user-images.githubusercontent.com/791670/200072425-424e9e8e-83aa-461e-b704-116a64c2a903.png">|<img width="1488" alt="CleanShot 2022-11-04 at 16 50 16@2x" src="https://user-images.githubusercontent.com/791670/200072422-b9f03562-b838-44a2-a200-182be1e5f8af.png">

## Testing in `sage-lib`

Visit the Grid views and verify that horizontal alignment changes looks the same in Rails and React:
- [Rails](http://localhost:4000/pages/patterns/grid#grid-alignment-horizontal)
- [React (Main Grid Example)](http://localhost:4100/?path=/story/sage-grid--default)
- [React (Horizontal Grid Example)](http://localhost:4100/?path=/story/sage-grid--horizontal-alignment)

## Testing in `kajabi-products`
1. (**LOW**) Added a way to toggle horizontal alignment to grid rows but didn't remove hardcoded classes which were already in place

## Related
[[DSS-214] - 12 Column Grid - Horizontal Alignment](https://kajabi.atlassian.net/browse/DSS-214)

2022-11-07 17:13 UTC, QuintonJason commented on docs/app/views/pages/grid.html.erb
> +  <p>The horizontal alignment default for each <code>.sage-row</code> container. This alignment will only be visible if the number of columns if the <strong>total</strong> columns is fewer than space
Can you reword the phrasing for this sentence

2022-11-07 17:16 UTC, QuintonJason approved these changes
Looks good

2022-11-07 19:05 UTC, QuintonJason commented
Is it possible to update the vertical alignment section to mirror this, with the demos and flushing out of the class? Really good stuff.

2022-11-07 20:40 UTC, goodwinchris commented
> Is it possible to update the vertical alignment section to mirror this, with the demos and flushing out of the class? Really good stuff.

https://kajabi.atlassian.net/browse/DSS-217

2022-11-07 21:51 UTC, goodwinchris commented
As per call with @ju-Skinner, I need to add some info to the react story in the notes section

2022-11-07 22:08 UTC, monkeypox8 commented on docs/lib/sage_rails/app/sage_components/sage_grid_row.rb
> +    horizontalAlignment: [:optional, String],
I'd recommend renaming as `horizontal_alignment` (snake case) over `horizontalAlignment`. Helps keep in line with our current patterns ([see `html_attributes` above](https://github.com/Kajabi/sage-lib/pull/1632/files#diff-3f47476a775c311dbe78f55b75b6ceb529bfbc5fa719c874b765c541165f32e9R386)), to follow the overall eng [Ruby style guide](https://kajabi.atlassian.net/wiki/spaces/ENG/pages/121438420/Ruby+Style+Guide#Syntax)

2022-11-07 22:13 UTC, pixelflips requested changes
A minor comment on prop naming and then I think it's good to go!

2022-11-07 22:13 UTC, pixelflips commented on docs/app/views/pages/grid.html.erb
> +    horizontalAlignment: "space-between",
on the rails side, I believe we typically use `_` instead of camel for prop naming.

2022-11-08 20:32 UTC, goodwinchris commented on packages/sage-react/lib/Grid/GridRow.story.mdx
> +  <Grid style={{ border: '1px solid grey' }}>
How do we feel about this???

2022-11-08 20:57 UTC, ju-Skinner reviewed
See comments for discussion.

2022-11-08 20:57 UTC, ju-Skinner commented on packages/sage-react/lib/Grid/GridRow.jsx
> +      [`sage-row--align-${horizontalAlignment}`]: horizontalAlignment,
What does this look like should the value be `null`. Should we have a default value of say `HORIZONTAL_ALIGNMENT_TYPES.Start`

2022-11-08 20:57 UTC, ju-Skinner commented on packages/sage-react/lib/Grid/GridRow.jsx
> +  horizontalAlignment: null,
should we have a default value? See previous comment.

2022-11-08 20:57 UTC, ju-Skinner commented on packages/sage-react/lib/Grid/GridRow.story.mdx
> +sample mdx for GridRow component, which is a subcomponent of [Grid](?path=/docs/sage-grid--default)
I would suggest to either take this out or provide a bit more detail here.

2022-11-08 20:57 UTC, ju-Skinner commented on packages/sage-react/lib/Grid/GridRow.story.mdx
> +  <Grid style={{ border: '1px solid grey' }}>
Can you elaborate a little bit more on this? My interpretation in your question is that should we call out what the parent component. I don't think it is necessary for a couple of reasons in this case...
1. It's in the name of the story `Grid`Item. 
2. The story is categorized within the parent.

2022-11-09 18:56 UTC, pixelflips approved these changes
Outside of Julian's latest comments, this LGTM! Nice work! 👍🏼

2022-11-09 19:55 UTC, goodwinchris commented on packages/sage-react/lib/Grid/GridRow.jsx
> +      [`sage-row--align-${horizontalAlignment}`]: horizontalAlignment,
I don't think there should be an issue here. I assume we don't want to generate a modifier unless `horizontalAlignment` is specifically passed and `Start` should display the same as the `normal` which is the default value.

2022-11-09 19:56 UTC, goodwinchris commented on packages/sage-react/lib/Grid/GridRow.jsx
> +  horizontalAlignment: null,
Not sure its needed, our grids don't break without it and many are using grids without it now so I feel it should be an entirely optional property.

2022-11-09 20:06 UTC, goodwinchris commented on packages/sage-react/lib/Grid/GridRow.story.mdx
> +sample mdx for GridRow component, which is a subcomponent of [Grid](?path=/docs/sage-grid--default)
I've removed it in alignment of our docs for `Grid` which don't have anything other than the heading on the page.

2022-11-15 20:00 UTC, pixelflips approved these changes
One non-blocking comment, but LGTM! Nice work! 👍🏼

2022-11-15 20:00 UTC, pixelflips commented on packages/sage-react/lib/Grid/GridNotes.story.mdx
> +
Links on this page are broken and pointing to the old URLs. Could these be updated or should they be adjusted in a follow-up? I'll let you decide.

2022-11-15 20:40 UTC, goodwinchris commented on packages/sage-react/lib/Grid/GridNotes.md
> +The `Grid.Row` and `Grid.Col` compositional elements can be added inside the `Grid` (with or without a `container`) in order to create complex layouts. As is documented on the [Sage Design System's G
This link is still broken but removing this file in next commit anyway

2022-11-15 22:41 UTC, QuintonJason commented on packages/sage-react/lib/Grid/configs.js
> +  Start: 'start',
Can these properties be all caps to align with the rest of the `config.js` files?

2022-11-16 14:29 UTC, QuintonJason approved these changes
Good to go

2022-11-16 16:12 UTC, ju-Skinner commented on packages/sage-react/lib/Grid/configs.js
> +  Start: 'start',
Since going to all caps for the attribute names....you will need to use an underscore the the attributes that have two words e.g `SpaceBetween` becomes `SPACE_BETWEEN`

2022-11-16 18:36 UTC, ju-Skinner approved these changes
Good job!!!!

2022-11-16 18:58 UTC, merged