[DSS-142] Modal - Size Update
Kajabi/sage-lib pull request #1646
Opened 2022-12-01 22:55 UTC by anechol

## Description

Updates the available sizes for the Modal component.

Note: There will be another PR to address changes in `kp` for the bump.

## Screenshots

|  Before  |  After  |
|--------|--------|
|||

## Testing in `sage-lib`

## Testing in `kajabi-products`

1. (**LOW/MEDIUM/HIGH/BREAKING**) Description of the change and its impact with QA as the audience.
   - [ ] One more examples of the component in use to either test the change or verify the change has not had adverse effects.

## Related

[DSS-142](https://kajabi.atlassian.net/browse/DSS-142)

2022-12-05 20:59 UTC, ju-Skinner requested changes
Reason for rejection is to centralize values in `SageTokens::MODAL_SIZES`

2022-12-05 20:59 UTC, ju-Skinner commented on docs/lib/sage_rails/app/sage_components/sage_modal.rb
> +    size: [:optional, NilClass, Set.new(["sm", "md", "lg", "mobile"])]
Lets create another variable called "MODAL_SIZES" in `SageTokens`.

2022-12-05 21:01 UTC, pixelflips reviewed
Left a comment on size naming. Also seeing the buttons are breaking out of the modal when using mobile size.

<img width="508" alt="Screen Shot 2022-12-05 at 12 54 53 PM" src="https://user-images.githubusercontent.com/1175111/205741908-e496c043-473a-4f42-8577-59267b967ad7.png">

2022-12-05 21:01 UTC, pixelflips commented on docs/lib/sage_rails/app/sage_components/sage_modal.rb
> +    size: [:optional, NilClass, Set.new(["sm", "md", "lg", "mobile"])]
Not a show-stopper, but any thoughts on using more consistent naming like `xs` instead of `mobile`? 

This is also more in line with naming in other areas such as `CONTAINER_SIZES`, `ICON_SIZES`, & `SPACER_SIZES`

2022-12-06 20:57 UTC, anechol commented on docs/lib/sage_rails/app/sage_components/sage_modal.rb
> +    size: [:optional, NilClass, Set.new(["sm", "md", "lg", "mobile"])]
This has been updated.

2022-12-06 20:57 UTC, anechol commented on docs/lib/sage_rails/app/sage_components/sage_modal.rb
> +    size: [:optional, NilClass, Set.new(["sm", "md", "lg", "mobile"])]
I agree here. Changed the size naming and fixed the broken example.

2022-12-06 21:33 UTC, merged