[DSS-245] Rich Text Editor followup
Kajabi/sage-lib pull request #1666
Opened 2023-01-03 16:31 UTC by QuintonJason

## Description

- [x] align ToolbarEditor demo to the design files - [ToolbarEditor design spec](https://www.figma.com/file/sMbtLUHSt2vfKgKjyQ3052/branch/E9ZMgX9QN2hnGlMAhSMWsl/%F0%9F%A7%A9-Sage-components?node-id=14813%3A35031&t=4xfziQIs33OpuodT-1)
- [x] resolve issue with gap between sections
- [x] resolve button in buttons of the dropdown items

## Screenshots

|  Before  |  After  |
|--------|--------|
|||

## Testing in `sage-lib`

[Toolbar Editor React view](http://localhost:4100/?path=/docs/sage-toolbareditor--default)

## Testing in `kajabi-products`

1. (**LOW**) Style updates to component with minimal usage.
   - [ ] Newsletter -> Issue -> Edit

## Related

[DSS-245](https://kajabi.atlassian.net/browse/DSS-245)

2023-01-04 17:30 UTC, anechol approved these changes
Very awesome work here! Just one extremely minor nitpick but non-blocking:
<img width="60" alt="Screen Shot 2023-01-04 at 11 26 38 AM" src="https://user-images.githubusercontent.com/14791307/210614507-99f5ac72-b3f4-496a-96a6-e3eec23dd24b.png">

Some spacing here is throwing the icon off center.

2023-01-04 19:09 UTC, goodwinchris commented
> Very awesome work here! Just one extremely minor nitpick but non-blocking: <img alt="Screen Shot 2023-01-04 at 11 26 38 AM" width="60" src="https://user-images.githubusercontent.com/14791307/210614507-99f5ac72-b3f4-496a-96a6-e3eec23dd24b.png">
> 
> Some spacing here is throwing the icon off center.

+1: seeing all icons lacking centering in their containers. Looks like all thats needed is a `justify-content: center;` on `.sage-btn::before`

2023-01-04 19:12 UTC, goodwinchris approved these changes

2023-01-04 20:00 UTC, ju-Skinner requested changes
There is more that we need to include on Responsiveness of this component. What do I mean by that, is there is some backend functionality that doesn't showcase itself unless you are in the code. 

Ideas that I have:
* New section titled "Responsive Behavior" <- Title up to you
  * Speak to how the "ToolEditorGroups" grow or shrink based on container size
   * Explain `isFlexible` ties into the that
 * Imagery 
   * Option 1: Possibly screen record behavior. Write captions and/or sections speaking to what is happening the vidoe
   * Option 2: Create screenshot with Annotations (Group 1, Group 2, Group 3) 
![image](https://user-images.githubusercontent.com/1633290/210639145-76f79ae3-6c99-4da9-93bf-5d12b40b8da9.png)

    Explain the differences and behaviors of the 2 - 3 groups in this example.
* Expectations of nested components. (optional)
  * Currently we are expecting a single nested level of components...e.g
  ```
  <ToolbarEditorGroup>
    <button>...</button>
  </ToolbarEditorGroup>
  ```

2023-01-06 22:19 UTC, QuintonJason commented
> There is more that we need to include on Responsiveness of this component. What do I mean by that, is there is some backend functionality that doesn't showcase itself unless you are in the code.
> 
> Ideas that I have:
> 
> * New section titled "Responsive Behavior" <- Title up to you
>   
>   * Speak to how the "ToolEditorGroups" grow or shrink based on container size
>   * Explain  how `isFlexible` ties into the that
> * Imagery
>   
>   * Option 1: Possibly screen record behavior. Write captions and/or sections speaking to what is happening the video
>   * Option 2: Create screenshot(s) with Annotations (Group 1, Group 2, Group 3)
>     ![image](https://user-images.githubusercontent.com/1633290/210640558-790e093a-e067-4566-97cc-0f53c8cab6cf.png)
>   
>   Explain the differences and behaviors of the four groups in this example.
>   Group 1: isFlexible=false, Single component
>   Group 2: isFlexible=false, three items, with specific dropdown to show  additional button commands
>   Group 3:  Only room for one icon, but the down chevron indicate more button commands available. Icon used is based on the first button command in the ToolbarEditorGroup
>   Group 4: standard ToolbarGroup that will expand and collapse based on available width. Plus sign icon indicates that there are items, unless there is only room for one. See description in Group 3 above
> * Expectations of nested components. (optional)
>   
>   * Currently we are expecting a single nested level of components...e.g
>   
>   ```
>   <ToolbarEditorGroup>
>     <button>...</button>
>   </ToolbarEditorGroup>
>   ```

@ju-Skinner all items were updated minus a loom video. I created on here, https://www.loom.com/share/ed64e018fb0b4bd09a698c69f42845cf, but I can't figure out how to add it to mdx

2023-01-11 16:11 UTC, ju-Skinner commented on packages/sage-react/lib/Toolbar/ToolbarEditorDocs.story.mdx
> +and the section's width is fixed only to the size of the inner elements.
I'm not sure if I'm struggling a bit here, but correct me if I'm wrong. 

>When disabled, the dropdown is no longer available
and the section's width is fixed only to the size of the inner elements.
Are you saying that when this property is set to `false` that the dropdown will no longer be available?

2023-01-11 16:14 UTC, ju-Skinner commented on packages/sage-react/lib/Toolbar/ToolbarEditorDocs.story.mdx
> +The `isFixed` property toggles the presence and behavior of the `<ToolbarEditor />` dropdown. Set to `false` by default, this property is meant to remove the responsive behavior. When disabled, the d
>The `isFixed` property toggles the presence and behavior of the `<ToolbarEditor />` dropdown.

Not sure if this is a better way or not, I would replace `<ToolbarEditor />` with the `add icon` dropdown. This seems to keep consistency with the verbiage you used in the previous section above.

2023-01-11 16:21 UTC, ju-Skinner commented on packages/sage-react/lib/Toolbar/ToolbarEditorDocs.story.mdx
> +
I'm not sure if this is to describe the example or suggesting the order which groups can and/or should be defined. 

It's to my understanding that the Toolbar groups can be defined as the implementor sees fit. Is that not the case?

2023-01-12 15:39 UTC, QuintonJason commented on packages/sage-react/lib/Toolbar/ToolbarEditorDocs.story.mdx
> +
@ju-Skinner I'm not sure of a place on the kp where we would put implementation document for components. This is something I can add in a followup to find an overall solution for components instead of this one.

2023-01-12 16:17 UTC, ju-Skinner commented on packages/sage-react/lib/Toolbar/ToolbarEditorDocs.story.mdx
> +
A follow up is fine with me.

2023-01-12 17:56 UTC, ju-Skinner approved these changes
Good job...much appreciate you taking my recommendations into consideration.

2023-01-13 20:13 UTC, merged