[DSS-297] Design hero updates
Kajabi/sage-lib pull request #1716
Opened 2023-03-13 22:48 UTC by pixelflips

## Description
Updates hero component to include new variant and related UI changes based on design audit.

## Screenshots

|  Before  |  After  |
|--------|--------|
|||

## Testing in `sage-lib`

## Testing in `kajabi-products`

1. (**LOW/MEDIUM/HIGH/BREAKING**) Description of the change and its impact with QA as the audience.
   - [ ] One more examples of the component in use to either test the change or verify the change has not had adverse effects.

## Related

2023-03-15 00:03 UTC, QuintonJason commented on packages/sage-react/lib/Hero/Hero.jsx
> +import { HERO_SIZES, } from './configs';
Can you remove this `,`?

2023-03-15 00:22 UTC, QuintonJason commented on packages/sage-assets/lib/stylesheets/components/_hero.scss
> +
Remove this line break

2023-03-15 00:23 UTC, QuintonJason commented on packages/sage-assets/lib/stylesheets/components/_hero.scss
> +    max-height: rem(235px);
Can you put this value in a var?

2023-03-15 00:24 UTC, QuintonJason commented on packages/sage-assets/lib/stylesheets/components/_hero.scss
> +    margin: rem(36px);
Can this one use the margin var from above?

2023-03-15 00:31 UTC, QuintonJason requested changes
This changes look great! I'm requesting the React side also be more aligned with respect to demos. On the Rails side we have a bunch:
- Default
- Contained
- w/ CTA
- Contained w/ CTA
- Borderless with Custom Background

Would you be able to add the following stories?
- Default
- Contained
- w/ CTA
- Borderless with Custom Background

2023-03-15 17:15 UTC, pixelflips commented on packages/sage-react/lib/Hero/Hero.jsx
> +import { HERO_SIZES, } from './configs';
Done.

2023-03-20 13:33 UTC, QuintonJason approved these changes
Looks and works great!

2023-03-21 21:37 UTC, anechol requested changes
Nice work here! Just added some comments for design spec stuff.

2023-03-21 21:37 UTC, anechol commented on packages/sage-assets/lib/stylesheets/components/_hero.scss
>    @extend %t-sage-heading-4;
Should this be heading-3?

2023-03-21 21:37 UTC, anechol commented on packages/sage-assets/lib/stylesheets/components/_hero.scss
>  .sage-hero__body {
Can we update this to match the design spec? The font-weight says 450 in the design file for this text, but it should be `medium` as medium = book. It's a long story...

2023-03-21 21:37 UTC, anechol commented on packages/sage-assets/lib/stylesheets/components/_hero.scss
>    margin-bottom: $-hero-margin-y;
Should this be 24px?

2023-03-21 21:37 UTC, anechol commented on packages/sage-react/lib/Hero/Hero.jsx
> +            <Button.Group gap="sm">
Should this be md?

2023-03-21 21:55 UTC, pixelflips commented
> Nice work here! Just added some comments for design spec stuff.

@anechol thanks so much for catching those! I was so focused on the new image/layout I missed some of those smaller details. It's a big yes to all of those and I've updated them. Thanks again!

2023-03-22 15:52 UTC, anechol requested changes
Thanks for making those changes. Just a couple more small things. It looks like the button gap between the CTAs should be 24px over 16px

2023-03-22 15:52 UTC, anechol commented on packages/sage-assets/lib/stylesheets/components/_hero.scss
>    margin-bottom: $-hero-margin-y;
I'm still seeing 32px here

2023-03-22 16:17 UTC, pixelflips commented on packages/sage-assets/lib/stylesheets/components/_hero.scss
>    margin-bottom: $-hero-margin-y;
@anechol should be good to go now. Thanks so much for catching those!

2023-03-22 16:36 UTC, anechol approved these changes
LGTM!! 🚀

2023-03-22 18:02 UTC, merged