Storybook Theme: Sage-ify Storybook
Kajabi/sage-lib pull request #1790
Opened 2023-08-24 15:45 UTC by monicawheeler

## Description

Storybook theming, which aligns with the theme we are implementing in Pine. This update provides an improved UI to ensure our users know they are in the right place.

### Changes
* Add favicon
* Add Sage logo
* Darken text throughout the UI
* Update the sidebar background

## Screenshots

|  Before  |  After  |
|--------|--------|
| ![before](https://github.com/Kajabi/sage-lib/assets/24237393/dbae7fd8-2bea-4708-a415-1d502b664080) | ![after](https://github.com/Kajabi/sage-lib/assets/24237393/7f37c916-ebe7-4d43-b503-9584da8ad053) |

## Testing in `sage-lib`
1. Navigate to http://localhost:4100/?path=/docs/introduction--page
2. View the majesty of changes 

## Testing in `kajabi-products` (KP)
1. (**LOW**) - No KP testing necessary

2023-08-24 15:54 UTC, ju-Skinner requested changes
Per our discussion via Huddle. We do want some element of surprise when releasing Pine. So we will remove the themeing of Sage's storybook, but keep the Favicon and Logo.

2023-08-24 15:56 UTC, pixelflips approved these changes
LGTM! 👍🏼 - Nice work!

2023-08-24 15:56 UTC, pixelflips commented on packages/sage-react/.storybook/SageTheme.js
> +  textColor: 'black',
Not a blocker whatsoever, but any thoughts on a slightly lighter shade? https://uxmovement.com/content/why-you-should-never-use-pure-black-for-text-or-backgrounds/

2023-08-24 18:54 UTC, ju-Skinner approved these changes
Great job. :shipit:

2023-08-25 15:51 UTC, anechol approved these changes

2023-08-25 15:53 UTC, merged