Modal Docs (Rails)
Kajabi/sage-lib pull request #1811
Opened 2023-10-11 22:01 UTC by QuintonJason

## Description

Update Form Modal documentation to better explain props in Rails.

## Screenshots

|  Before  |  After  |
|--------|--------|
|<img width="1588" alt="Screenshot 2023-10-11 at 3 58 24 PM" src="https://github.com/Kajabi/sage-lib/assets/1241836/607466a4-461e-45bf-a93c-588dc87f257b">|<img width="1389" alt="Screenshot 2023-10-11 at 3 58 37 PM" src="https://github.com/Kajabi/sage-lib/assets/1241836/3c10639c-b9cd-4f76-834d-35c26bae2782">|

## Testing in `sage-lib`

## Testing in `kajabi-products`

1. (**LOW/MEDIUM/HIGH/BREAKING**) Description of the change and its impact with QA as the audience.
   - [ ] One more examples of the component in use to either test the change or verify the change has not had adverse effects.

## Related

2023-10-16 21:10 UTC, pixelflips requested changes
Left one minor comment on adding dividers to match other docs updates.

The only other feedback is we may need a better description copy for the top of the page, but not a showstopper right now. Could be updated in a follow-up if needed. 

Otherwise, this is a great update! Really nice work!

2023-10-16 21:10 UTC, pixelflips commented on docs/app/views/examples/components/modal/_preview.html.erb
Can we can get `SageDivider` added between the different sections? See the button for example.

2023-10-17 16:01 UTC, pixelflips commented on docs/app/helpers/components_helper.rb
> +        description: "Modals are overlays used to display content on a layer above the page, preventing users from interacting with content behind the modal.",
🔥

2023-10-19 16:58 UTC, ju-Skinner approved these changes

2023-10-19 19:58 UTC, monicawheeler commented on docs/app/views/examples/components/modal/_preview.html.erb
> +<p>Modals can be configured to be extra small, small, medium, or large.</p>
Could we clarify that this adjusts the width of the modal?

2023-10-19 20:02 UTC, monicawheeler commented on docs/app/views/examples/components/modal/_preview.html.erb
> +    title: "Delete item",
This should probably be updated to "Modal Header" rather than "Delete item"

2023-10-19 20:04 UTC, monicawheeler commented on docs/app/views/examples/components/modal/_preview.html.erb
> +    help_content: "<p>Are you sure you want to delete this item? This action cannot be undone.</p>",
This should not indicate a delete to avoid confusing engineers copying this modal.

2023-10-19 20:04 UTC, monicawheeler commented on docs/app/views/examples/components/modal/_preview.html.erb
> +    title: "Delete item",
This should probably be updated to "Modal Header" rather than "Delete item"

2023-10-19 20:04 UTC, monicawheeler commented on docs/app/views/examples/components/modal/_preview.html.erb
> +    help_content: "<p>Are you sure you want to delete this item? This action cannot be undone.</p>",
Same as previous comment about "delete" text

2023-10-19 20:05 UTC, monicawheeler commented on docs/app/views/examples/components/modal/_preview.html.erb
> +<h3 class=\"SageClassnames::TYPE::HEADING_6\">Asynchronous Modal Setup</h3>
We should be able to remove the `class` here

2023-10-19 20:07 UTC, monicawheeler commented on docs/app/views/examples/components/modal/_preview.html.erb
> +<h3 class=\"SageClassnames::TYPE::HEADING_6\">Asynchronous Modal Setup</h3>
Do any of the steps correlate with the Open modal A, B, or C buttons? Could we clarify what those buttons are demonstrating? Thank you!

2023-10-24 19:58 UTC, monicawheeler approved these changes

2023-10-24 21:34 UTC, anechol approved these changes

2023-10-25 16:58 UTC, merged