[DNM] [WIP] docs(loader): update the react loader documentation
Kajabi/sage-lib pull request #1812
Opened 2023-10-11 22:04 UTC by ju-Skinner

## Description
This is an attempt to update the Documentation for both the Rails and React Loader component.

2023-10-17 21:50 UTC, pixelflips requested changes
A few typos and suggestions. Once the typos are done, it's ready to go! Really nice update here!

2023-10-17 21:50 UTC, pixelflips commented on packages/sage-react/lib/Loader/Loader.story.mdx
> +When using the compoennt in its default state, it will use the default type of `SPINNER`
Typo for the word component.

2023-10-17 21:50 UTC, pixelflips commented on packages/sage-react/lib/Loader/Loader.story.mdx
> +    <Loader loading={true} label="My loading label...." types={Loader.TYPES.BAR} />
This type is set to Bar, but is displaying as a spinner.

2023-10-17 21:50 UTC, pixelflips commented on packages/sage-react/lib/Loader/Loader.story.mdx
> +This loading indictator is good when you want to provide feedback to the user that they are typing.
Should indictator be indicator?

2023-10-17 21:50 UTC, pixelflips commented on docs/app/views/examples/components/loader/_preview.html.erb
>    <div class="sage-col--md-6 example__block--lg">
Not a show-stopper at all, but if you wanted to remove the usage of the hard-coded classes you could update the rows and cols to something like the following. I'll let you make the call! 

```
<%= sage_component SageGridRow, {} do %>
  <%= sage_component SageGridCol, { size: 6, css_classes: "example__block--lg" } do %>
    LEFT COL CONTENT
  <% end %>
  <%= sage_component SageGridCol, { size: 6, css_classes: "example__block--lg" } do %>
    RIGHT COL CONTENT
  <% end %>
<% end %>
```

2023-10-17 22:03 UTC, pixelflips approved these changes
LGTM! Awesome improvement here! Great work! 👍🏼

2023-10-24 14:37 UTC, monicawheeler commented on packages/sage-react/lib/Loader/Loader.story.mdx
> +The continuous spinner is used when loading progress cannont be determined. They indicate to the user
Small spelling update
```suggestion
The continuous spinner is used when loading progress cannot be determined. They indicate to the user
```

2023-10-24 14:38 UTC, monicawheeler commented on packages/sage-react/lib/Loader/Loader.story.mdx
> +Seting this property will hide the loader when the process/request has been completed.
Small spelling update
```suggestion
Setting this property will hide the loader when the process/request has been completed.
```

2023-10-24 14:44 UTC, monicawheeler commented on packages/sage-react/lib/Loader/Loader.story.mdx
> +    <Loader loading={true} label="My loading label...." type={Loader.TYPES.BAR} />
The `bar` loader type does not work with the label option because of the nature of the bar styles (overflow is hidden) - let's switch this example to `spinner` and update the text above to, `Allows you to provide custom text to the Spinner loader.`

2023-10-24 14:45 UTC, monicawheeler requested changes
Made a couple of spelling comments and an example update.

2023-10-24 14:49 UTC, monicawheeler approved these changes
Thanks for the super prompt updates! Looks great!

2023-10-24 14:57 UTC, merged

2023-10-24 15:04 UTC, anechol reviewed
Nice work! Just one small thing to update.

2023-10-24 15:04 UTC, anechol commented on packages/sage-react/lib/Loader/Loader.jsx
>    fillSpace: PropTypes.bool,
If `fillSpace` is deprecated, can we reflect that in the args table?