Dss 477/dropdown horizontal and vertical repositioning
Kajabi/sage-lib pull request #1822
Opened 2023-10-18 21:30 UTC by QuintonJason

## Description

- [x] Rails update horizontal repositioning so that modal doesn't hang off the screen
- [ ] React update horizontal repositioning so that modal doesn't hang off the screen 

## Screenshots

|  Before  |  After  |
|--------|--------|
||![Kapture 2023-10-18 at 16 24 48](https://github.com/Kajabi/sage-lib/assets/1241836/0771a2ae-d40d-4555-94b3-b4ca02967292)|

## Testing in `sage-lib`

## Testing in `kajabi-products`

1. (**LOW/MEDIUM/HIGH/BREAKING**) Description of the change and its impact with QA as the audience.
   - [ ] One more examples of the component in use to either test the change or verify the change has not had adverse effects.

## Related

2023-10-19 17:04 UTC, ju-Skinner commented on packages/sage-system/lib/dropdown.js
> +
looks like you have extra whitespace here.

2023-10-19 17:05 UTC, ju-Skinner commented on packages/sage-system/lib/dropdown.js
> +
extra whitespace here as well.

2023-10-19 17:05 UTC, ju-Skinner commented on packages/sage-system/lib/dropdown.js
> +
extra whitespace here as well.

2023-10-19 17:05 UTC, ju-Skinner commented on packages/sage-system/lib/dropdown.js
> +
extra whitespace here as well.

2023-10-19 17:06 UTC, ju-Skinner requested changes
Just fix the whitespace issues. Other than that things are good.

2023-10-19 19:02 UTC, pixelflips approved these changes
A couple of `console.log` and the whitespace mentioned by Julian, otherwise great work!

2023-10-19 19:02 UTC, pixelflips commented on packages/sage-system/lib/dropdown.js
> +    console.log('directionY', directionY);
Should these be removed?

2023-10-19 23:51 UTC, pixelflips approved these changes

2023-10-24 14:02 UTC, ju-Skinner approved these changes

2023-10-25 15:34 UTC, anechol approved these changes
🚀

2023-10-25 16:41 UTC, merged