Feat/hero image start
Kajabi/sage-lib pull request #1828
Opened 2023-10-23 18:38 UTC by monicawheeler

## Description

## Screenshots

|  Before  |  After  |
|--------|--------|
|||

## Testing in `sage-lib`

## Testing in `kajabi-products`

1. (**LOW/MEDIUM/HIGH/BREAKING**) Description of the change and its impact with QA as the audience.
   - [ ] One more examples of the component in use to either test the change or verify the change has not had adverse effects.

## Related

2023-10-30 20:53 UTC, ju-Skinner requested changes
Looks great overall..One small fix in the Hero.jsx file. 

* Set default prop value to `false` instead of `null`.

2023-10-30 20:53 UTC, ju-Skinner commented on packages/sage-react/lib/Hero/Hero.jsx
> +  imageStart: null,
`bool` values should either be set to `true` or `false` for default values.  Since you are setting it to `null`, default should be `false`

2023-10-30 20:53 UTC, ju-Skinner commented on packages/sage-react/lib/Hero/Hero.jsx
> +  imageStart: null,
I know you didn't make the change, but I would apply the same rule to the following props

`borderless` and `contained`,

2023-10-30 21:23 UTC, pixelflips requested changes
A few comments to note a few small issues.


NOTE:
Non-blocking, but any thoughts on the story naming, just to help keep the sidebar a bit more tidy? 

Something like the following might work ok since they are the major ones that aren't used in every instance. No strong preference here, but just a thought so feel free to ignore.

- Sizes
- Borderless
- Contained
- Custom Background
- Image Start
- CTA Attribute

2023-10-30 21:23 UTC, pixelflips commented on packages/sage-react/lib/Hero/Hero.story.mdx
> +### Small - contained
Seeing some odd image sizing on the contained images:

<img width="745" alt="Screenshot 2023-10-30 at 2 05 47 PM" src="https://github.com/Kajabi/sage-lib/assets/1175111/84f7b6ab-d5aa-4df0-95e9-7375b444d01d">

2023-10-30 21:23 UTC, pixelflips commented on packages/sage-react/lib/Hero/Hero.story.mdx
> +      ctaAttributes={{
Not entirely sure what the issue is, but I am getting a related JS error:

<img width="749" alt="Screenshot 2023-10-30 at 2 05 17 PM" src="https://github.com/Kajabi/sage-lib/assets/1175111/ceb84d5a-99be-44e1-85bc-bf4522032b66">

Note: it may not be this exact instance, but seems related to `ctaAttributes`.

2023-10-30 21:23 UTC, pixelflips commented on packages/sage-react/lib/Hero/Hero.story.mdx
> +<Canvas>
I think the borderless prop is missing on the borderless examples.

2023-10-30 21:23 UTC, pixelflips commented on packages/sage-react/lib/Hero/Hero.story.mdx
> +<ArgsTable story="Small - full-bleed" />
Props table is not loading for me.

<img width="1059" alt="Screenshot 2023-10-30 at 2 16 36 PM" src="https://github.com/Kajabi/sage-lib/assets/1175111/a7acc44a-665a-4986-8c5c-3324e6fa70b7">

2023-10-30 21:38 UTC, monicawheeler commented on packages/sage-react/lib/Hero/Hero.jsx
> +  imageStart: null,
Thank you for the feedback! Updated!

2023-10-30 21:40 UTC, pixelflips reviewed
Also noticed the React Component link on the Docs site will need to be updated as it currently points to default (`/docs/sage-hero--default`) which is no longer there.

2023-10-30 21:42 UTC, monicawheeler commented on packages/sage-assets/lib/stylesheets/components/_hero.scss
> +  @media (min-width: 1200px) {
Good catch! Updated!

2023-10-30 21:43 UTC, monicawheeler commented on packages/sage-react/lib/Hero/Hero.story.mdx
> +### Small - contained
Try pulling in the latest changes. This was missing the contained prop.

2023-10-30 21:44 UTC, monicawheeler commented on packages/sage-react/lib/Hero/Hero.story.mdx
> +<ArgsTable story="Small - full-bleed" />
See if pulling the latest on the branch helps. I had this issue but fixed it with a more recent commit.

2023-10-30 21:46 UTC, pixelflips commented on packages/sage-react/lib/Hero/Hero.story.mdx
> +### Small - contained
That did it! 🙌🏼

2023-10-30 21:48 UTC, monicawheeler commented on packages/sage-react/lib/Hero/Hero.story.mdx
> +<Canvas>
Good catch on this one, too! Thanks! Updated!

2023-10-30 21:55 UTC, monicawheeler commented
> Looks great overall..One small fix in the Hero.jsx file.
> 
>     * Set default prop value to `false` instead of `null`.

Sorry but which prop? or line?

2023-10-30 21:56 UTC, monicawheeler commented
> Also noticed the React Component link on the Docs site will need to be updated as it currently points to default (`/docs/sage-hero--default`) which is no longer there.

@pixelflips - this should also be resolved now that you have the current commits! Let me know if not!

2023-10-30 21:57 UTC, monicawheeler commented
> A few comments to note a few small issues.
> 
> NOTE: Non-blocking, but any thoughts on the story naming, just to help keep the sidebar a bit more tidy?
> 
> Something like the following might work ok since they are the major ones that aren't used in every instance. No strong preference here, but just a thought so feel free to ignore.
> 
>     * Sizes
> 
>     * Borderless
> 
>     * Contained
> 
>     * Custom Background
> 
>     * Image Start
> 
>     * CTA Attribute

@pixelflips - thank you for the feedback and thoughts! I think this organization makes more sense and I'll update both React and Rails to align.

2023-10-30 22:00 UTC, pixelflips commented
> > Also noticed the React Component link on the Docs site will need to be updated as it currently points to default (`/docs/sage-hero--default`) which is no longer there.
> 
> @pixelflips - this should also be resolved now that you have the current commits! Let me know if not!

@monicawheeler Yup, good to go. Not sure how I didn't have the latest, but sorry for all the confusion.

2023-10-30 22:51 UTC, monicawheeler commented on packages/sage-react/lib/Hero/Hero.story.mdx
> +      ctaAttributes={{
@pixelflips - I took a look, fiddled with the proptypes, but having trouble clearing this. I'll take a look tomorrow!

2023-10-31 16:06 UTC, ju-Skinner approved these changes
Great work.

2023-11-07 15:48 UTC, monicawheeler commented on packages/sage-react/lib/Hero/Hero.story.mdx
> +      ctaAttributes={{
Huge thanks to @ju-Skinner for helping me solve this issue and get this out the door! 🙌🏻

2023-11-07 16:58 UTC, merged