Fix warnings for React files
Kajabi/sage-lib pull request #1889
Opened 2024-05-16 19:38 UTC by monicawheeler

## Description
`yarn lint` was returning 14 warnings related to "React Hook useEffect or useCallback has a missing dependency", and "Unexpected console statement." This issue addresses those warnings.

## Screenshots
No visual changes.

## Testing in `sage-lib`
1. Pull PR locally
2. Navigate to the fixed React files in Storybook and verify they work as expected
  a. http://localhost:4100/?path=/story/sage-drawer--default
  b. http://localhost:4100/?path=/story/sage-input--default
  c. http://localhost:4100/?path=/story/sage-panelcontrols--default
  d. http://localhost:4100/?path=/story/sage-table--default-story
  e. http://localhost:4100/?path=/story/sage-toast--default
  f. http://localhost:4100/?path=/story/sage-switch--default
  g. http://localhost:4100/?path=/story/sage-typeahead--default
  h. http://localhost:4100/?path=/docs/sage-tooltip--default

## Testing in `kajabi-products`
1. (**MEDIUM**) Resolving warnings may affect functionality.

## Related
[DSS-449](https://kajabi.atlassian.net/browse/DSS-449)

## Warning specifics
```/sage-lib/packages/sage-react/lib/Drawer/Drawer.jsx
  43:6  warning  React Hook useEffect has a missing dependency: 'onExpandChange'. Either include it or remove the dependency array. If 'onExpandChange' changes too often, find the parent component that defines it and wrap that definition in useCallback  react-hooks/exhaustive-deps

/sage-lib/packages/sage-react/lib/Input/Input.jsx
  106:6  warning  React Hook useEffect has a missing dependency: 'inputStyles'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

/sage-lib/packages/sage-react/lib/Input/Input.story.jsx
  154:5  warning  Unexpected console statement  no-console

/sage-lib/packages/sage-react/lib/PanelControls/PanelControls.story.jsx
  150:6  warning  React Hook useEffect has a missing dependency: 'fetchData'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

/sage-lib/packages/sage-react/lib/Table/Table.jsx
  176:6  warning  React Hook useEffect has a missing dependency: 'buildHeaders'. Either include it or remove the dependency array      react-hooks/exhaustive-deps
  182:6  warning  React Hook useEffect has a missing dependency: 'getSelectionType'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

/sage-lib/packages/sage-react/lib/Table/TableRow.jsx
  79:6  warning  React Hook useEffect has a missing dependency: 'hasBorders'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

/sage-lib/packages/sage-react/lib/Toast/Toast.jsx
  45:6  warning  React Hook useEffect has a missing dependency: 'dismiss'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
  50:6  warning  React Hook useEffect has a missing dependency: 'dismiss'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

/sage-lib/packages/sage-react/lib/Toggle/Switch.story.jsx
  106:37  warning  Using propTypes from another component is not safe because they may be removed in production builds  react/forbid-foreign-prop-types

/sage-lib/packages/sage-react/lib/Tooltip/TooltipElement.jsx
  68:6  warning  React Hook useLayoutEffect has missing dependencies: 'parentDomRect' and 'position'. Either include them or remove the dependency array. Mutable values like 'tooltipRef.current' aren't valid dependencies because mutating them doesn't re-render the component  react-hooks/exhaustive-deps

/sage-lib/packages/sage-react/lib/Typeahead/Typeahead.jsx
  42:38  warning  React Hook useEffect has a missing dependency: 'filterList'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

/sage-lib/packages/sage-react/lib/common/hooks/useDebounceEffect.jsx
  4:20  warning  React Hook useCallback has a missing dependency: 'effect'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

/sage-lib/packages/sage-react/lib/common/hooks/useFocusTrap.jsx
  65:6  warning  React Hook useEffect has missing dependencies: 'containerRef', 'onDeactivateFn', and 'returnFocus'. Either include them or remove the dependency array. Mutable values like 'containerRef.current' aren't valid dependencies because mutating them doesn't re-render the component  react-hooks/exhaustive-deps

✖ 14 problems (0 errors, 14 warnings)```

2024-05-16 19:39 UTC, ju-Skinner commented on packages/sage-react/lib/Input/Input.jsx
> +  }, [prefix, suffix, inputStyles]);
Be careful with these types of things...they can sometimes cause unexpected side effects. I would suggest you test these manually.

2024-05-16 23:21 UTC, QuintonJason requested changes
![Screenshot 2024-05-16 at 6 20 21 PM](https://github.com/Kajabi/sage-lib/assets/1241836/965b4b07-f57d-4c66-8682-0cfeb97d9f4f)

Getting the following warning in the browser console

2024-05-17 14:50 UTC, monicawheeler commented
> ![Screenshot 2024-05-16 at 6 20 21 PM](https://private-user-images.githubusercontent.com/1241836/331411155-965b4b07-f57d-4c66-8682-0cfeb97d9f4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTc2MzUsIm5iZiI6MTcxNTk1NzMzNSwicGF0aCI6Ii8xMjQxODM2LzMzMTQxMTE1NS05NjViNGIwNy1mNTdkLTRjNjYtODY4Mi0wY2ZlYjk3ZDlmNGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTdUMTQ0ODU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjZhNzVlODYxYWZmNDQ5YmI1NDY2N2E5YWVjMzg5Yzg1MGExMDY3NjkxOWQ0ZjVjOGI4MDllMTNhZTE2NDEyYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mIZ5OycgtXdiglH78uqlcskLr6H0BWfHFSrROBLchhM)
> 
> Getting the following warning in the browser console

These are different from what I sought to resolve. These errors occur on the production side as well. What are your thoughts of dealing with those in another task?

2024-05-28 19:06 UTC, monicawheeler commented on packages/sage-react/lib/Input/Input.jsx
> +  }, [prefix, suffix, inputStyles]);
@ju-Skinner - I did manually test these in the local dev environment for the doc site, and all the functionality and styles worked as expected. Anything in particular you suggest I look out for?

2024-05-28 19:31 UTC, ju-Skinner commented on packages/sage-react/lib/Input/Input.jsx
> +  }, [prefix, suffix, inputStyles]);
Let's consider disabling these instead of trying to add the dependency. This could have an adverse side-effect that we may not catch until it's in prod.

2024-06-17 16:20 UTC, QuintonJason approved these changes
Looks great and console is error-free

2024-06-17 16:33 UTC, ju-Skinner approved these changes

2024-06-17 18:05 UTC, merged