Sage: Integrate Pine into icons
Kajabi/sage-lib pull request #1890
Opened 2024-05-17 19:04 UTC by monicawheeler

Rough planning phase currently. **Do not merge.**

## Description

## Screenshots

|  Before  |  After  |
|--------|--------|
|||

## Testing in `sage-lib`

## Testing in `kajabi-products`

1. (**LOW/MEDIUM/HIGH/BREAKING**) Description of the change and its impact with QA as the audience.
   - [ ] One more examples of the component in use to either test the change or verify the change has not had adverse effects.

## Related

2024-05-17 19:13 UTC, monicawheeler commented on docs/app/views/application/_app_head_content.html.erb
> +<script type="module" src="https://cdn.jsdelivr.net/npm/@pine-ds/core/dist/pine-core/pine-core.esm.js"></script>
Adds the pine icon library in rails in order to serve the web components.

2024-05-17 19:14 UTC, monicawheeler commented on package.json
> +    "@pine-ds/icons": "^4.2.0"
Adds pine-ds/icons as a sage-react dependency

2024-05-17 19:14 UTC, monicawheeler commented on packages/sage-react/.storybook/manager-head.html
> +<script type="module" src="http://localhost:7200/build/pds-icons.esm.js"></script>
brings in the locally run pds-icons files

2024-05-17 19:14 UTC, monicawheeler commented on packages/sage-react/lib/Icon/Icon.jsx
> +import { downSmall } from '@pine-ds/icons/icons';
tests a specific named icon - likely not necessary but used during testing

2024-05-17 19:15 UTC, monicawheeler commented on packages/sage-react/lib/Icon/Icon.jsx
> +  // const sizeMapping = {
commented out but left to ensure we account for differences between what pine is using and what sage react needs - this needs to be addressed

2024-05-17 19:15 UTC, monicawheeler commented on packages/sage-react/lib/Icon/Icon.jsx
> +    <i>
wrapped in `i` to test - not necessarily needed

2024-05-17 19:16 UTC, monicawheeler commented on packages/sage-react/lib/Icon/Icon.jsx
> +      <pds-icon name={downSmall} />
testing a specific icon name from the import - this was in effort to troubleshoot the pds-icon not outputting the shadow root

2024-05-17 19:16 UTC, monicawheeler commented on packages/sage-react/package.json
> +    "@kajabi/sage-assets": "^1.14.5",
updating for sage bump

2024-05-17 19:17 UTC, monicawheeler commented on packages/sage-react/package.json
> +    "@pine-ds/icons": "^4.2.0",
added to utilize pine-ds/icons 🤔 - is this necessary if we are importing the js files directly into the manager-head.thml

2024-05-20 14:17 UTC, monicawheeler commented on packages/sage-react/package.json
> +    "@pine-ds/icons": "^4.2.0",
I am looking for info, not offering direction with this comment.

2024-05-28 16:53 UTC, ju-Skinner commented on docs/app/views/application/_nav.html.erb
> +    <!-- COMING SOON
we need to close the comment ` -->`

2024-05-28 17:01 UTC, pixelflips commented on docs/app/views/application/_nav.html.erb
> +    <!-- COMING SOON
i think it is closed, it's just a few lines down ~63.

2024-05-28 19:21 UTC, ju-Skinner commented on docs/app/views/application/_nav.html.erb
> +    <!-- COMING SOON
Yep...you're right. I'm marking this resolved.

2024-05-29 21:03 UTC, anechol requested changes
Icons are coming in fine in Rails, but I can't see them on the React side. Additionally, because of them being web components, there is now a fraction of a second on page load with no cache where the icon isn't showing up. I can't imagine there will be complaints about it, but just making a note of it here, since this is being updated app-wide.

2024-05-29 21:10 UTC, pixelflips commented
> Icons are coming in fine in Rails, but I can't see them on the React side. Additionally, because of them being web components, there is now a fraction of a second on page load with no cache where the icon isn't showing up. I can't imagine there will be complaints about it, but just making a note of it here, since this is being updated app-wide.

You will need to be running your local pine for the react side. Also, make sure the ports match your local instance in the `packages/sage-react/.storybook/preview-head.html` file.

2024-05-30 14:52 UTC, QuintonJason approved these changes
After changing line 86 of `packages/sage-react/package.json` to ` "@kajabi/sage-assets": "*",` and restarted the server, everything was good to go

2024-05-30 19:16 UTC, monicawheeler commented
@pixelflips - the Category item page has an alert, http://localhost:4000/pages/component/catalog_item?tab=preview, is missing the icon 
| Local | Live |
|--------|--------|
| ![Screenshot 2024-05-30 at 2 15 41 PM](https://github.com/Kajabi/sage-lib/assets/24237393/4cf68179-c837-4903-9d5f-fce72940151b) | ![Screenshot 2024-05-30 at 2 15 45 PM](https://github.com/Kajabi/sage-lib/assets/24237393/fc1d76cc-b149-43e7-b88c-fc934249aaf1) |

2024-05-30 19:21 UTC, monicawheeler commented
Property is missing the icons
http://localhost:4000/pages/component/property?tab=preview
![Screenshot 2024-05-30 at 2 21 20 PM](https://github.com/Kajabi/sage-lib/assets/24237393/b9857a45-4ab4-4a15-a103-8ceadc5f7523)

2024-05-30 19:23 UTC, monicawheeler commented
Typeahead is missing the icons in the dropdown
![Screenshot 2024-05-30 at 2 22 54 PM](https://github.com/Kajabi/sage-lib/assets/24237393/f67c7e01-00be-415a-b676-14e7c3e21a6d)

2024-05-30 19:34 UTC, pixelflips commented
@monicawheeler those should all be addressed now, docs just had incorrect icon naming.

alert icons - done
property - done / forgot to push the commit for this one
typeahead - done

2024-05-30 19:56 UTC, monicawheeler commented
![Screenshot 2024-05-30 at 2 38 27 PM](https://github.com/Kajabi/sage-lib/assets/24237393/ee44ebbf-a945-4bc2-b6ac-3985ee6f0022)
On local, the arrows are not aligned properly in react

2024-05-30 19:59 UTC, pixelflips commented
> On local, the arrows are not aligned properly in react

@monicawheeler before checking storybook, please apply the changes from quinton's comment above.

2024-05-30 20:00 UTC, monicawheeler commented
![Screenshot 2024-05-30 at 2 59 40 PM](https://github.com/Kajabi/sage-lib/assets/24237393/458a10b3-bf29-4ca0-b17b-8626e17b6b22)
Could we verify the button spacing between icons is consistent with the documentation? It appears wider in the local dev environment on react compared to the public url

2024-05-31 14:37 UTC, monicawheeler commented
> > On local, the arrows are not aligned properly in react
> 
> @monicawheeler before checking storybook, please apply the `package.json` changes from quinton's comment above.

This is still an issue for me after pulling and updating the `packages/sage-react/package.json` file per Quinton's comments.

2024-05-31 14:37 UTC, monicawheeler commented
> ![Screenshot 2024-05-30 at 2 59 40 PM](https://private-user-images.githubusercontent.com/24237393/335361479-458a10b3-bf29-4ca0-b17b-8626e17b6b22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNjY0MzUsIm5iZiI6MTcxNzE2NjEzNSwicGF0aCI6Ii8yNDIzNzM5My8zMzUzNjE0NzktNDU4YTEwYjMtYmYyOS00Y2EwLWIxN2ItODYyNmUxN2I2YjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE0MzUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhM2ZhODZmZDkyY2E1OWY1OThkYzA4MDk1ZmI3Zjg4NTliMDMzZDJjZGU1MGRiZmI3MjRlZWMxMDkzODQ5YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nHcOV6JlTSBFY4HvnF5vF5v0oDC2ONBDPcCXA_gOP1E) Could we verify the button spacing between icons is consistent with the documentation? It appears wider in the local dev environment on react compared to the public url

This is resolved after pulling latest and following Quinton's `packages/sage-react/package.json` update.

2024-06-03 17:26 UTC, ju-Skinner commented on docs/app/views/examples/components/panel/_preview.html.erb
> +        <%= sage_component SageIcon, { icon: "video-on" } %>
Question why did we elect to use `SageIcon` here versus `pds-icon`? I see in some instances we went from `<i...` to `<pds-icon...`

Not blocking, but just wanted to call this out for consistency

2024-06-03 17:28 UTC, ju-Skinner commented on package.json
> +    "@pine-ds/icons": "^4.2.0"
we may need to up this to the latest version of [Pine Icons](https://www.npmjs.com/package/@pine-ds/icons)...currently v6.0.0

2024-06-03 17:31 UTC, ju-Skinner commented on packages/sage-react/lib/Dropdown/Dropdown.jsx
> +    if (!el) return;
Looks like we need to rebase...This has been handled elsewhere.

2024-06-03 17:32 UTC, ju-Skinner approved these changes

2024-06-03 17:33 UTC, monicawheeler reviewed
Since I authored this PR, I cannot Approve. I did not do the work here though and after a review, I add my ✅ - This is good to go and great work!

2024-06-04 19:18 UTC, anechol requested changes
Nice work getting these updated!

Can we update the Banner component as well? That icon is missing.

2024-06-04 19:55 UTC, pixelflips commented
> Nice work getting these updated!
> 
> Can we update the Banner component as well? That icon is missing.

@anechol great catch! those should be updated now as well.

2024-06-06 19:51 UTC, merged