Style/update heading font weights
Kajabi/sage-lib pull request #1912
Opened 2024-07-18 18:46 UTC by ju-Skinner

## Description
Headings will now use 100 based scale (100...900), where the body will now use *25 scale (125...925)

## Screenshots
### Body - NO CHANGE
|  Before  |  After  |
|--------|--------|
|![image](https://github.com/user-attachments/assets/1c3673e6-c5b9-4fb5-a420-442886ad0909)|![image](https://github.com/user-attachments/assets/a1391158-e415-4ae9-93c2-0087001d5790)|

### Headings
|  Before  |  After  |
|--------|--------|
|![image](https://github.com/user-attachments/assets/5c4609e4-9e8a-477d-85ca-d423b3c453ee)|![image](https://github.com/user-attachments/assets/522578d2-d196-4d73-8004-e5adbf3adea4)|

## Testing in `sage-lib`
1. Navigate to Foundation -> Typography http://localhost:4000/pages/foundations/typography
2. Inspect Paragraph (*25) and Headings (*00), 

## Related
https://kajabi.atlassian.net/browse/DSS-720

2024-07-18 18:48 UTC, pixelflips approved these changes
🔥 Nice approach! LGTM!

2024-07-22 15:28 UTC, QuintonJason requested changes
Requesting changes because of the design decision to likely change fro SF Pro to Roboto. We don't know if these will remain valid

2024-07-23 17:50 UTC, QuintonJason approved these changes
Verified with design that the headings will remain *00s and body will remain *25s

2024-07-24 14:08 UTC, monicawheeler commented on packages/sage-assets/lib/stylesheets/tokens/_font_weight.scss
> +@function sage-font-weight($key: regular, $heading: false) {
🙌

2024-07-24 14:09 UTC, monicawheeler approved these changes

2024-07-24 17:14 UTC, merged