Sage Null View
Kajabi/sage-lib pull request #267
Opened 2021-01-27 17:32 UTC by pixelflips

## Description
Adds new null_view into Sage.

### Screenshots

|  LG Screens  |  SM Screens  |
|--------|--------|
|![Screen Shot 2021-01-27 at 9 28 47 AM](https://user-images.githubusercontent.com/1175111/106029702-3409bb00-6082-11eb-88a1-32f4aee79495.png)|![Screen Shot 2021-01-27 at 9 29 06 AM](https://user-images.githubusercontent.com/1175111/106029748-3d932300-6082-11eb-866c-718e21985af9.png)|

### Steps for testing
1. http://localhost:4000/pages/breakout/object/null_view
2. Verify UI and check object properties.

## Related

- N/A

2021-01-27 17:53 UTC, philschanely requested changes
Very nice work here! I've a few responsive-related changes suggested here and some other comments. LMK if you'd like to pair! 🙇

2021-01-27 17:53 UTC, philschanely commented on packages/sage-assets/lib/stylesheets/patterns/objects/_null_view.scss
> +  .sage-null-view {
So glad you considered responsiveness! We don't have a lot of this as reference yet in our system. As we move forward, I'd prefer to see these responsive adjustments nested within each respective selector. Either way we repeat something, but IMO placing them with the selector allows one to see the properties better. It would also be my preference for any affected styles to be guarded. So in the case of `.sage-null-view__content`, we might have this:

```scss
.sage-null-view__content {
  display: flex;
  align-items: flex-start;
  flex-direction: column;
  justify-content: center;
  flex-wrap: wrap;
  
  @media screen and (max-width: sage-breakpoint(sm-max)) {
    order: 2;
  }
  
  @media screen and (min-width: sage-breakpoint(md-min)) {
    order: 1;
  }
}
```

2021-01-27 17:53 UTC, philschanely commented on packages/sage-assets/lib/stylesheets/patterns/objects/_null_view.scss
> +    &.sage-null-view {
Is this specificity necessary?

2021-01-27 17:53 UTC, philschanely commented on packages/sage-assets/lib/stylesheets/patterns/objects/_null_view.scss
> +    .sage-null-view__content {
These should probably be done as:

```scss
.sage-null-view__content {
  ...
  .sage-null-view--reversed & { ... }
}
```

2021-01-27 17:53 UTC, philschanely commented on docs/lib/sage_rails/app/views/sage_components/_sage_null_view.html.erb
> +    <p class="sage-null-view__text"><%= component.text %></p>
Any consideration of leaving this content area more open such as for multiple paragraphs or additional formatting?

2021-01-27 17:53 UTC, philschanely commented on docs/app/views/examples/objects/null_view/_props.html.erb
> +  <td><code>title</code></td>
Side note that we can use the `md()` function for markdown formatting in documentation like this. See Card Highlight props as one example.

2021-01-28 01:06 UTC, monkeypox8 approved these changes
👍🏼 LGTM, nice work! A few suggestions to consider; nothing that should be blocking.

2021-01-28 01:06 UTC, monkeypox8 commented on docs/lib/sage_rails/app/views/sage_components/_sage_null_view.html.erb
> +    <div class="sage-null-view__graphic">
I think you should be able to ditch container here, and just apply the class directly on the image. Grid gets weird with scaling images, though.

2021-01-28 15:36 UTC, joedakroub approved these changes
This looks terrific Phillip! Very nice work. I added one comment about a suggestion that @monkeypox8 made, but not a blocker. Thanks! 👍🏼

2021-01-28 15:36 UTC, joedakroub commented on packages/sage-assets/lib/stylesheets/patterns/objects/_null_view.scss
> +  order: 2;
This is a great suggestion about reversing the markup order over using `order` in this context. 👍🏼

2021-01-28 15:47 UTC, philschanely commented on docs/lib/sage_rails/app/views/sage_components/_sage_null_view.html.erb
> +    <div class="sage-null-view__graphic">
FWIW I'm in favor of keeping the wrapper for additional flexibility in sizing, scaling, cropping, etc. of the graphic.

2021-01-28 15:48 UTC, philschanely approved these changes
Pending fixes based on suggestions from others, looking great here! 👍

2021-01-28 18:44 UTC, merged