Update docs config for Rails
Kajabi/sage-lib pull request #358
Opened 2021-03-03 20:31 UTC by nobodyiscertain

## Description

### Screenshots

|  Before  |  After  |
|--------|--------|
|||

## Test notes

### Estimated impact

- [ ] (**LOW/MEDIUM/HIGH/BREAKING** impact level) Description of change and examples of use. Address to cross-functional groups when needed.

## Related

2021-03-03 20:46 UTC, nobodyiscertain commented on docs/Procfile
> -web: npm run rails:server:production
This was requiring us to need the node buildpack, which I think we don't need if we just use Ruby.

2021-03-03 20:48 UTC, nobodyiscertain commented on docs/app/helpers/application_helper.rb
> +require "pp"
After assets were compiling, it was barking about not having `pretty_inspect`. I thought that Pretty Print was auto-included in Ruby, but thinking it might not be available in production? Little confused about this honestly, but this gets it working.

2021-03-03 20:49 UTC, nobodyiscertain commented on docs/Procfile
> +web: bundle exec rails server -e production -b 0.0.0.0 -p $PORT
I'm not sure we should be using WEBrick (rails s) for production. But thinking we could swap it to puma/unicorn in a follow-up.

2021-03-03 21:02 UTC, voodooGQ requested changes
Just one note, I have it as "request changes" until we can have someone in UX vet out the local Kajabi bridge and the Kajabi Products integration.

2021-03-03 21:02 UTC, voodooGQ commented on docs/package.json
> +    "css-loader": "^5.1.1",
Putting these as part of the primary dependencies may present conflicts when using the Sage bridge or when integrating into Kajabi Products. We should make sure to test these thoroughly before moving forward.

2021-03-03 21:42 UTC, philschanely commented
Pulled, bootstrapped, and checked `kajabi-products` with the bridge per @voodooGQ 's suggestion. No concerns here! 

👍  from me and THANK YOU!

2021-03-03 21:58 UTC, nobodyiscertain commented on docs/package.json
> +    "css-loader": "^5.1.1",
Ah, good thinking! Looks like @philschanely was able to confirm we're good with the bridge. How can we check it with Kajabi Products? Should we get QA involved?

2021-03-04 00:17 UTC, voodooGQ approved these changes
Sorry for the late approve! If @philschanely feels good about it then I'm on board. Thank you!

2021-03-04 00:37 UTC, merged