BUILD-1145: podcast search not working
Kajabi/sage-lib pull request #543
Opened 2021-05-25 21:40 UTC by justinjkim

## Description
BUILD-1145

Podcast episode search was not working when you searched for something on a page different than what the episode was on. This was because adding the search filter on top of a pagination tried to look for that search result on that specific page. The solution was to remove the `page` key from the `URLSearchParams`.

## Screenshots

|  Before  |  After  |
|--------|--------|
| ![Screen Shot 2021-05-25 at 2 35 33 PM](https://user-images.githubusercontent.com/15473295/119571970-e0c12400-bd66-11eb-876f-e048d9436dc0.png) | ![Screen Shot 2021-05-25 at 2 36 20 PM](https://user-images.githubusercontent.com/15473295/119571993-ed457c80-bd66-11eb-892e-4c08f8af7e0c.png) |

## Testing in `sage-lib`

## Testing in `kajabi-products`

1. (**MEDIUM**) Description of the change and its impact with QA as the audience.
   - [ ] One more examples of the component in use to either test the change or verify the change has not had adverse effects.

## Related

2021-05-26 14:34 UTC, philschanely reviewed
Thanks @justinjkim . One question below.

(looks like a rebase may be needed too)

2021-05-26 14:34 UTC, philschanely commented on packages/sage-system/lib/search.js
> +      searchParams.delete('page'); // BUILD-1145: pagination for search results won't work if the `page` key is set to something other than 1, so we need this deletion of the `page` key
I don't know much about how this is working in `products` so trust to your needs here. Has this addition been tested in any other pages that use the SageSearch to verify it does not create a breaking change elsewhere?

2021-05-26 23:00 UTC, justinjkim commented on packages/sage-system/lib/search.js
> +      searchParams.delete('page'); // BUILD-1145: pagination for search results won't work if the `page` key is set to something other than 1, so we need this deletion of the `page` key
Hey Phil! I did test on some other searches, but will verify with Monica and Quinton to make sure. Thanks!

2021-05-27 13:35 UTC, monicawheeler requested changes
I tested within Contacts in `kajabi-products` and it appears the issue is not resolved.

Testing steps:
1. 
![step1](https://user-images.githubusercontent.com/24237393/119835292-55f73b00-bec6-11eb-9c19-b80d5efd4f01.png)
2. 
![step1 result](https://user-images.githubusercontent.com/24237393/119835311-5a235880-bec6-11eb-8103-59f1f108aa71.png)
3. 
![step2](https://user-images.githubusercontent.com/24237393/119835355-61e2fd00-bec6-11eb-86d7-690fd420cdf3.png)
4. 
![step2 result](https://user-images.githubusercontent.com/24237393/119835371-65768400-bec6-11eb-9943-c5e57b03e8e2.png)

2021-05-27 19:45 UTC, monicawheeler approved these changes
Verified with @justinjkim on pairing session that the `SageSearch` component does work properly after this fix.

2021-05-27 19:48 UTC, justinjkim commented on packages/sage-system/lib/search.js
> +      searchParams.delete('page'); // BUILD-1145: pagination for search results won't work if the `page` key is set to something other than 1, so we need this deletion of the `page` key
Hi @philschanely , looks like on the Rails pages that utilize `SageSearch`, this fix does work. Can't speak to the React version of the components, they still seem to be WIP, but I can check with the devs working on those pages.

2021-05-27 19:48 UTC, merged