Loader - improve loading indicator
Kajabi/sage-lib pull request #86
Opened 2020-12-04 23:16 UTC by QuintonJason

## Description

made style improvements to the bar and spinner loader

### Screenshots

|  before  |  after  |
|--------|--------|
|![loaders-before](https://user-images.githubusercontent.com/1241836/101224422-27558180-3654-11eb-9c9c-25f562cbcb14.gif)|![loaders-after](https://user-images.githubusercontent.com/1241836/101224435-2de3f900-3654-11eb-961f-91abd806ca3d.gif)|

## Test notes

### Steps for testing
1. Visit the loader page: http://localhost:4000/pages/element/loader

2020-12-07 16:40 UTC, philschanely reviewed
Very cool! Does this have Design input as well? Seems they may be interested in the use of gradients.

2020-12-07 16:50 UTC, AndrwM requested changes
This is looking great, nice stuff.

Could we match the args between the Rails and React implementations?

Does this support existing in a small context (within the Outline Items when info is being loaded)? I know there was chatter about this at one point but I'm not sure where we landed in terms of a spec.

Let's wait to merge this until we have the new Sage landed so that we can spin up a accompanying Kajab-Products branch.

2020-12-07 16:50 UTC, AndrwM commented on docs/app/views/examples/elements/loader/_preview.html.erb
>        loader_type: "bar"
What do you think of naming this `shape` instead of `loader_type` so that we're matching the arguments for this component across React/Rails?

I'm open to `type` for both as well as long as we're consistent.

2020-12-07 16:50 UTC, AndrwM commented on packages/sage-react/lib/Loader/Loader.jsx
> +    'aria-live': "polite"
I haven't seen this before. Cool :D

2020-12-07 20:09 UTC, monkeypox8 approved these changes
👍 LGTM, looks smooth! Added a couple of nitpicky comments below, non-blockers.

2020-12-07 20:09 UTC, monkeypox8 commented on packages/sage-assets/lib/stylesheets/patterns/elements/_loader.scss
> +    background: sage-color(primary, 300);
Could we use `background-color` here? The `background` shorthand sets a handful of default properties we may not want in this case.

2020-12-11 15:39 UTC, AndrwM approved these changes
Once final nits are addressed this has my +1. 💯

2020-12-11 15:39 UTC, AndrwM commented on docs/lib/sage_rails/app/sage_components/sage_loader.rb
>    attr_accessor :style
Please remove the `:style` attr since we're no longer using

2020-12-11 15:39 UTC, AndrwM commented on docs/app/views/examples/elements/loader/_props.html.erb
> +</tr>
This file should be updated to reflect the names of the attrs. (`type` instead of `loader_type`).

2020-12-11 16:08 UTC, philschanely approved these changes
Very nice work @QuintonJason . Two tidying comments. 🥇

2020-12-11 16:08 UTC, philschanely commented on docs/lib/sage_rails/app/views/sage_components/_sage_loader.html.erb
> +    <svg class="spinner" viewBox="25 25 50 50" >
Could these also use `sage-` classnames and BEM?

2020-12-11 16:08 UTC, philschanely commented on packages/sage-react/lib/Loader/Loader.jsx
> +  type: PropTypes.oneOf(Object.values(LOADER_SHAPES)),
If we're switching the `type` instead of `shape` could we also update the config variable name to `LOADER_TYPES`?

2020-12-11 17:50 UTC, merged