[Sage-802] Expandable Card Alignment Prop
Kajabi/sage-lib pull request #875
Opened 2021-10-08 21:40 UTC by anechol

## Description

Adds a new prop to the Expandable Card component to allow arrow alignment to the right.

## Screenshots

|  Before  |  After  |
|--------|--------|
WIP|WIP

## Testing in `sage-lib`

WIP

## Testing in `kajabi-products`

1. (**LOW/MEDIUM/HIGH/BREAKING**) Description of the change and its impact with QA as the audience.
   - [ ] One more examples of the component in use to either test the change or verify the change has not had adverse effects.
WIP

## Related

Closes #802

2021-10-12 15:57 UTC, monicawheeler requested changes
Looks great! One additional item to include: the documentation for `align_right` within `docs/app/views/examples/components/expandable_card/_props.html.erb`

2021-10-12 17:54 UTC, philschanely reviewed
Looking good here. A few comments regarding nested SCSS practice. Also, I agree with your technique for the styling but wonder if there's a clearer label for the property. `align_right` leaves it a little unclear to me what will be aligned or affected. So something like `button_arrow_align_right` makes it clearer. It also relates to the button filling the space available so i could see `button_fill_width` as another idea to consider. What do you think?

Lastly, a quick audit of this component's use might also indicate whether or not this could switch to being the default setting.

2021-10-12 17:54 UTC, philschanely commented on packages/sage-assets/lib/stylesheets/components/_expandable_card.scss
> +  .sage-btn {
FWIW our practice so far has been to place styles like this in the selected element's file: button in this case, and to therefor do this kind of selection:

```scss
.sage-btn {
  // other existing button styles here
  
.sage-expandable-card--align-right & {
    // styles here
  }
}
```

The hope is to keep all styles affecting a given component within that component, and thus have a standard when there's places like this that could go either way. You could still leave a comment in this file regarding that aspect if that seems good to you.

2021-10-12 17:54 UTC, philschanely commented on packages/sage-assets/lib/stylesheets/components/_expandable_card.scss
> +  .sage-btn__truncate-text {
Same deal here, in that this could move over to be alongside other styles for `sage-btn__truncate-text` in `button.scss`.

2021-10-13 19:05 UTC, anechol commented
@monkeypox8 Thanks for catching that. I've removed the margin.

A more uniform naming convention across Sage would be beneficial in my opinion, especially if it sounds more like well-known CSS values. Could definitely be something to consider.

2021-10-13 19:06 UTC, merged